"""Render deploy/.env.example from the schema."""

from __future__ import annotations

from .schema import FEATURE_TITLES, FEATURES, KEYS

HEADER = (
    "# QJudge deployment settings.\n"
    "# Generated by `deploy/qjudge env-example`; edit deploy/qjudge_cli/schema.py instead.\n"
    "# Copy to deploy/.env, fill in values, then run `deploy/qjudge check`.\n"
    "# Commented keys are optional or required only for the feature they belong to."
)


def render() -> str:
    lines = [HEADER]
    for feature in FEATURES:
        lines.append("")
        lines.append(f"# --- {FEATURE_TITLES[feature]} ---")
        for key in KEYS:
            if key.feature != feature:
                continue
            lines.append(f"# {key.help}")
            prefix = "" if key.required is True else "# "
            lines.append(f"{prefix}{key.name}=")
    return "\n".join(lines) + "\n"
