"""Create deploy/.env for a new installation."""

from __future__ import annotations

import secrets
from pathlib import Path
from typing import Callable, Mapping

from .check import check_env
from .envfile import write_private
from .schema import KEYS, Key
from .stack import Runner, ensure_network

Ask = Callable[[Key], str]

GENERATED = {
    "SECRET_KEY": lambda: secrets.token_urlsafe(50),
    "POSTGRES_ADMIN_PASSWORD": lambda: secrets.token_urlsafe(24),
    "DB_PASSWORD": lambda: secrets.token_urlsafe(24),
    "AI_DB_PASSWORD": lambda: secrets.token_urlsafe(24),
    "CREDENTIAL_LEASE_SECRET": lambda: secrets.token_urlsafe(32),
}
# Optional keys worth offering during an interactive setup.
OFFERED = ("MEDIA_MODE", "FRONTEND_BIND_ADDRESS", "QJUDGE_TRUSTED_PROXIES")


def _mode_defaults(env: Mapping[str, str]) -> dict[str, Callable[[], str]]:
    defaults: dict[str, Callable[[], str]] = {}
    if env.get("STORAGE_MODE") == "bundled":
        defaults.update({
            "OBJECT_STORAGE_ENDPOINT_URL": lambda: "http://minio:9000",
            "OBJECT_STORAGE_ACCESS_KEY": lambda: "qjudge",
            "OBJECT_STORAGE_SECRET_KEY": lambda: secrets.token_urlsafe(24),
            "OBJECT_STORAGE_BUCKET": lambda: "qjudge",
        })
    if env.get("MEDIA_MODE") == "bundled":
        defaults.update({
            "LIVEKIT_API_KEY": lambda: secrets.token_hex(16),
            "LIVEKIT_API_SECRET": lambda: secrets.token_urlsafe(32),
        })
    return defaults


def _fill(env: dict[str, str], makers: Mapping[str, Callable[[], str]]) -> None:
    for name, make in makers.items():
        if not env.get(name, "").strip():
            env[name] = make()


def build_env(values: Mapping[str, str], ask: Ask | None = None) -> dict[str, str]:
    """Return values plus generated secrets and mode defaults; ask() fills
    the required keys that remain empty (and offers a few optional ones)."""
    env = {name: value.strip() for name, value in values.items()}
    _fill(env, GENERATED)
    offered = False
    while True:
        _fill(env, _mode_defaults(env))
        missing = [key for key in KEYS if key.is_required(env) and not env.get(key.name, "").strip()]
        if ask is None:
            return env
        if missing:
            env[missing[0].name] = ask(missing[0]).strip()
            continue
        if offered:
            return env
        offered = True
        for key in KEYS:
            if key.name in OFFERED and not env.get(key.name, "").strip():
                env[key.name] = ask(key).strip()


def render_env(env: Mapping[str, str]) -> str:
    lines = ["# Generated by `deploy/qjudge init`; see deploy/.env.example for every key."]
    lines += [f"{key.name}={env[key.name]}" for key in KEYS if env.get(key.name, "").strip()]
    return "\n".join(lines) + "\n"


def _prompt(key: Key) -> str:
    return input(f"{key.name}: {key.help}\n> ")


def run_init(
    deploy_dir: Path,
    env_file: Path,
    values: Mapping[str, str],
    interactive: bool,
    run: Runner,
    ask: Ask = _prompt,
) -> int:
    if env_file.exists():
        print(f"{env_file} already exists; edit it and run `deploy/qjudge check`")
        return 1
    env = build_env(values, ask if interactive else None)
    problems = check_env(env)
    for problem in problems:
        print(problem)
    if problems:
        return 1
    (deploy_dir / "secrets" / "integrity").mkdir(parents=True, exist_ok=True)
    write_private(env_file, render_env(env))
    ensure_network(run)
    print(f"Wrote {env_file}")
    if env.get("STORAGE_MODE") == "bundled":
        print("Next: deploy/qjudge addon storage up && deploy/qjudge addon storage init")
    if env.get("MEDIA_MODE") == "bundled":
        print("Next: deploy/qjudge addon media up")
    print("Then: deploy/qjudge ingress, and deploy/qjudge upgrade <git ref>")
    return 0
