"""The single list of keys a deployer sets in deploy/.env."""

from __future__ import annotations

from collections.abc import Callable, Mapping
from dataclasses import dataclass
from typing import Union

Env = Mapping[str, str]
Requirement = Union[bool, Callable[[Env], bool]]


@dataclass(frozen=True)
class Key:
    name: str
    feature: str
    help: str
    required: Requirement = False
    secret: bool = False

    def is_required(self, env: Env) -> bool:
        if callable(self.required):
            return bool(self.required(env))
        return self.required


FEATURES = ("core", "storage", "media", "ai", "oauth", "smtp", "mcp", "tunnel", "dev")

FEATURE_TITLES = {
    "core": "Core",
    "storage": "Object storage",
    "media": "Live monitoring (LiveKit)",
    "ai": "AI providers",
    "oauth": "Third-party login",
    "smtp": "Email",
    "mcp": "Remote MCP",
    "tunnel": "Cloudflare Tunnel",
    "dev": "Local development only",
}


def _media_enabled(env: Env) -> bool:
    return env.get("MEDIA_MODE", "") in {"bundled", "external"}


def _media_bundled(env: Env) -> bool:
    return env.get("MEDIA_MODE", "") == "bundled"


def _profile_enabled(profile: str) -> Callable[[Env], bool]:
    def requirement(env: Env) -> bool:
        profiles = [item.strip() for item in env.get("COMPOSE_PROFILES", "").split(",")]
        return profile in profiles

    return requirement


def _paired_with(other: str) -> Callable[[Env], bool]:
    def requirement(env: Env) -> bool:
        return bool(env.get(other, ""))

    return requirement


def _oauth_pair(provider: str, label: str) -> tuple[Key, Key]:
    client_id = f"{provider}_OAUTH_CLIENT_ID"
    client_secret = f"{provider}_OAUTH_CLIENT_SECRET"
    return (
        Key(client_id, "oauth", f"{label} OAuth client ID.",
            required=_paired_with(client_secret)),
        Key(client_secret, "oauth", f"{label} OAuth client secret.",
            required=_paired_with(client_id), secret=True),
    )


KEYS: tuple[Key, ...] = (
    # Core
    Key("QJUDGE_PUBLIC_ORIGIN", "core",
        "Origin users open in the browser, e.g. https://judge.example.edu (no path).",
        required=True),
    Key("GATEWAY_BIND_ADDRESS", "core",
        "Address the gateway listens on. Use the VPS private IP when the reverse proxy is on another machine."),
    Key("GATEWAY_PORT", "core", "Port the gateway listens on."),
    Key("QJUDGE_TRUSTED_PROXIES", "core",
        "Comma-separated IPs of the reverse proxy in front of the gateway."),
    Key("COMPOSE_PROJECT_NAME", "core", "Compose project name; keep it unchanged on existing hosts."),
    Key("COMPOSE_PROFILES", "core", "Optional Compose profiles, e.g. tunnel."),
    Key("SECRET_KEY", "core", "Django secret key. Generated by `qjudge init`.",
        required=True, secret=True),
    Key("POSTGRES_ADMIN_PASSWORD", "core",
        "PostgreSQL administrator password (letters, digits and -._~). Generated by `qjudge init`.",
        required=True, secret=True),
    Key("DB_PASSWORD", "core",
        "Application database password (letters, digits and -._~). Generated by `qjudge init`.",
        required=True, secret=True),
    Key("AI_DB_PASSWORD", "core",
        "AI database password (letters, digits and -._~). Generated by `qjudge init`.",
        required=True, secret=True),
    Key("CREDENTIAL_LEASE_SECRET", "core", "AI credential lease secret. Generated by `qjudge init`.",
        required=True, secret=True),
    # Object storage
    Key("STORAGE_MODE", "storage",
        "bundled runs MinIO as a QJudge addon; external uses an existing S3-compatible service.",
        required=True),
    Key("OBJECT_STORAGE_PUBLIC_ENDPOINT_URL", "storage",
        "Storage URL reachable from browsers; must be HTTPS when the origin is HTTPS.",
        required=True),
    Key("OBJECT_STORAGE_ENDPOINT_URL", "storage",
        "Storage URL reachable from containers. Written by `qjudge addon storage init` in bundled mode.",
        required=True),
    Key("OBJECT_STORAGE_ACCESS_KEY", "storage",
        "Storage access key. Written by `qjudge addon storage init` in bundled mode.",
        required=True, secret=True),
    Key("OBJECT_STORAGE_SECRET_KEY", "storage",
        "Storage secret key. Written by `qjudge addon storage init` in bundled mode.",
        required=True, secret=True),
    Key("OBJECT_STORAGE_BUCKET", "storage",
        "Bucket name. Written by `qjudge addon storage init` in bundled mode.",
        required=True),
    # Live monitoring
    Key("MEDIA_MODE", "media", "disabled, bundled (LiveKit addon) or external (existing LiveKit)."),
    Key("LIVEKIT_PUBLIC_URL", "media", "LiveKit URL browsers connect to, e.g. wss://live.example.edu.",
        required=_media_enabled),
    Key("LIVEKIT_API_KEY", "media", "LiveKit API key.", required=_media_enabled, secret=True),
    Key("LIVEKIT_API_SECRET", "media", "LiveKit API secret.", required=_media_enabled, secret=True),
    Key("LIVEKIT_NODE_IP", "media", "Public IP LiveKit advertises for media (bundled mode).",
        required=_media_bundled),
    Key("LIVEKIT_TURN_HOST", "media", "DNS-only TURN hostname (bundled mode).",
        required=_media_bundled),
    Key("LIVEKIT_TURN_SECRET", "media", "TURN shared secret (bundled mode).",
        required=_media_bundled, secret=True),
    # AI providers
    Key("OPENAI_API_KEY", "ai", "OpenAI API key.", secret=True),
    Key("OPENAI_BASE_URL", "ai", "OpenAI-compatible base URL override."),
    Key("DEEPSEEK_API_KEY", "ai", "DeepSeek API key.", secret=True),
    Key("DEEPSEEK_BASE_URL", "ai", "DeepSeek base URL override."),
    Key("VLLM_API_KEY", "ai", "Self-hosted vLLM API key.", secret=True),
    Key("VLLM_BASE_URL", "ai", "Self-hosted vLLM OpenAI-compatible URL."),
    # Third-party login
    *_oauth_pair("NYCU", "NYCU"),
    *_oauth_pair("GITHUB", "GitHub"),
    *_oauth_pair("GOOGLE", "Google"),
    # Email
    Key("EMAIL_HOST_USER", "smtp", "SMTP username.", required=_paired_with("EMAIL_HOST_PASSWORD")),
    Key("EMAIL_HOST_PASSWORD", "smtp", "SMTP password.",
        required=_paired_with("EMAIL_HOST_USER"), secret=True),
    # Remote MCP
    Key("QJUDGE_REMOTE_MCP_ENABLED", "mcp", "true exposes /mcp for external MCP clients."),
    # Cloudflare Tunnel
    Key("TUNNEL_TOKEN", "tunnel", "Cloudflare Tunnel token; required when COMPOSE_PROFILES includes tunnel.",
        required=_profile_enabled("tunnel"), secret=True),
    # Local development only
    Key("HOST_PROJECT_ROOT", "dev", "Absolute path of the checkout on the Docker host (local development)."),
    Key("DOCKER_JUDGE_PLATFORM", "dev", "Judge container platform, e.g. linux/amd64 on Apple Silicon."),
)

KEYS_BY_NAME: dict[str, Key] = {key.name: key for key in KEYS}
