# Generated by Django 4.2.26 on 2025-11-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="標題")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "簡單"), ("medium", "中等"), ("hard", "困難")],
                        default="medium",
                        max_length=10,
                        verbose_name="難度",
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(default=1000, verbose_name="時間限制 (ms)"),
                ),
                (
                    "memory_limit",
                    models.IntegerField(default=128, verbose_name="記憶體限制 (MB)"),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="是否可見")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "submission_count",
                    models.IntegerField(default=0, verbose_name="提交次數"),
                ),
                ("accepted_count", models.IntegerField(default=0, verbose_name="通過次數")),
            ],
            options={
                "verbose_name": "題目",
                "verbose_name_plural": "題目",
                "db_table": "problems",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField(verbose_name="輸入資料")),
                ("output_data", models.TextField(verbose_name="輸出資料")),
                ("is_sample", models.BooleanField(default=False, verbose_name="是否為範例")),
                ("score", models.IntegerField(default=0, verbose_name="分數")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_hidden", models.BooleanField(default=False, verbose_name="是否隱藏")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="problems.problem",
                        verbose_name="題目",
                    ),
                ),
            ],
            options={
                "verbose_name": "測試案例",
                "verbose_name_plural": "測試案例",
                "db_table": "test_cases",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProblemTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=10, verbose_name="語言代碼")),
                ("title", models.CharField(max_length=255, verbose_name="標題")),
                ("description", models.TextField(verbose_name="題目描述")),
                ("input_description", models.TextField(verbose_name="輸入說明")),
                ("output_description", models.TextField(verbose_name="輸出說明")),
                ("hint", models.TextField(blank=True, verbose_name="提示")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="problems.problem",
                        verbose_name="題目",
                    ),
                ),
            ],
            options={
                "verbose_name": "題目翻譯",
                "verbose_name_plural": "題目翻譯",
                "db_table": "problem_translations",
            },
        ),
    ]
