# Generated by Django 4.2.26 on 2025-11-30 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="標題")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "簡單"), ("medium", "中等"), ("hard", "困難")],
                        default="medium",
                        max_length=10,
                        verbose_name="難度",
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(default=1000, verbose_name="時間限制 (ms)"),
                ),
                (
                    "memory_limit",
                    models.IntegerField(default=128, verbose_name="記憶體限制 (MB)"),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="是否可見")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "submission_count",
                    models.IntegerField(default=0, verbose_name="提交次數"),
                ),
                ("accepted_count", models.IntegerField(default=0, verbose_name="通過次數")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_problems",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="建立者",
                    ),
                ),
            ],
            options={
                "verbose_name": "題目",
                "verbose_name_plural": "題目",
                "db_table": "problems",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField(verbose_name="輸入資料")),
                ("output_data", models.TextField(verbose_name="輸出資料")),
                ("is_sample", models.BooleanField(default=False, verbose_name="是否為範例")),
                ("score", models.IntegerField(default=0, verbose_name="分數")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_hidden", models.BooleanField(default=False, verbose_name="是否隱藏")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="problems.problem",
                        verbose_name="題目",
                    ),
                ),
            ],
            options={
                "verbose_name": "測試案例",
                "verbose_name_plural": "測試案例",
                "db_table": "test_cases",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProblemTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=10, verbose_name="語言代碼")),
                ("title", models.CharField(max_length=255, verbose_name="標題")),
                ("description", models.TextField(verbose_name="題目描述")),
                ("input_description", models.TextField(verbose_name="輸入說明")),
                ("output_description", models.TextField(verbose_name="輸出說明")),
                ("hint", models.TextField(blank=True, verbose_name="提示")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="problems.problem",
                        verbose_name="題目",
                    ),
                ),
            ],
            options={
                "verbose_name": "題目翻譯",
                "verbose_name_plural": "題目翻譯",
                "db_table": "problem_translations",
                "unique_together": {("problem", "language")},
            },
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["difficulty"], name="problems_difficu_cbb392_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["is_visible"], name="problems_is_visi_40a652_idx"
            ),
        ),
        migrations.CreateModel(
            name="LanguageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("cpp", "C++"),
                            ("python", "Python"),
                            ("java", "Java"),
                            ("javascript", "JavaScript"),
                        ],
                        max_length=20,
                        verbose_name="程式語言",
                    ),
                ),
                (
                    "template_code",
                    models.TextField(blank=True, default="", verbose_name="範本程式碼"),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="啟用")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_configs",
                        to="problems.problem",
                        verbose_name="題目",
                    ),
                ),
            ],
            options={
                "verbose_name": "語言設定",
                "verbose_name_plural": "語言設定",
                "db_table": "problem_language_configs",
                "ordering": ["order", "language"],
                "unique_together": {("problem", "language")},
            },
        ),
        migrations.AddField(
            model_name="problem",
            name="contest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contest_problems",
                to="contests.contest",
                verbose_name="所屬競賽",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="is_contest_only",
            field=models.BooleanField(default=False, verbose_name="僅限競賽"),
        ),
        migrations.AddField(
            model_name="problem",
            name="source_problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="problems.problem",
                verbose_name="來源題目",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="display_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="顯示編號"
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="Slug"
            ),
        ),
    ]
