# Generated by Django 4.2.30 on 2026-09-15 08:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodingProblem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(default=1000, verbose_name="時間限制 (ms)"),
                ),
                (
                    "memory_limit",
                    models.IntegerField(default=128, verbose_name="記憶體限制 (MB)"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "submission_count",
                    models.IntegerField(default=0, verbose_name="提交次數"),
                ),
                ("accepted_count", models.IntegerField(default=0, verbose_name="通過次數")),
                ("wa_count", models.IntegerField(default=0, verbose_name="答案錯誤次數")),
                ("tle_count", models.IntegerField(default=0, verbose_name="超時次數")),
                ("mle_count", models.IntegerField(default=0, verbose_name="記憶體超限次數")),
                ("re_count", models.IntegerField(default=0, verbose_name="執行錯誤次數")),
                ("ce_count", models.IntegerField(default=0, verbose_name="編譯錯誤次數")),
                (
                    "forbidden_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="提交代碼中不可出現的關鍵字列表 (substring match)",
                        verbose_name="禁用關鍵字",
                    ),
                ),
                (
                    "required_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="提交代碼中必須包含的關鍵字列表 (substring match)",
                        verbose_name="必須關鍵字",
                    ),
                ),
            ],
            options={
                "verbose_name": "題目",
                "verbose_name_plural": "題目",
                "db_table": "problems",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="標籤名稱"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "color",
                    models.CharField(
                        default="#0f62fe",
                        help_text="Hex color code for tag display",
                        max_length=7,
                        verbose_name="顏色",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "標籤",
                "verbose_name_plural": "標籤",
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField(verbose_name="輸入資料")),
                ("output_data", models.TextField(verbose_name="輸出資料")),
                ("is_sample", models.BooleanField(default=False, verbose_name="是否為範例")),
                ("score", models.IntegerField(default=0, verbose_name="分數")),
                (
                    "weight_percent",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="建議使用 0~100 的整數百分比；同題測資加總應為 100",
                        null=True,
                        verbose_name="權重百分比",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_hidden", models.BooleanField(default=False, verbose_name="是否隱藏")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="problems.codingproblem",
                        verbose_name="題目",
                    ),
                ),
            ],
            options={
                "verbose_name": "測試案例",
                "verbose_name_plural": "測試案例",
                "db_table": "test_cases",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LanguageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("cpp", "C++"),
                            ("python", "Python"),
                            ("java", "Java"),
                            ("javascript", "JavaScript"),
                        ],
                        max_length=20,
                        verbose_name="程式語言",
                    ),
                ),
                (
                    "template_code",
                    models.TextField(blank=True, default="", verbose_name="範本程式碼"),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="啟用")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_configs",
                        to="problems.codingproblem",
                        verbose_name="題目",
                    ),
                ),
            ],
            options={
                "verbose_name": "語言設定",
                "verbose_name_plural": "語言設定",
                "db_table": "problem_language_configs",
                "ordering": ["order", "language"],
            },
        ),
    ]
