# Generated by Django 4.2.26 on 2025-11-26 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("problems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_problems",
                to=settings.AUTH_USER_MODEL,
                verbose_name="建立者",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="problemtranslation",
            unique_together={("problem", "language")},
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["difficulty"], name="problems_difficu_cbb392_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["is_visible"], name="problems_is_visi_40a652_idx"
            ),
        ),
    ]
