# Generated by Django 4.2.30 on 2026-09-15 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("question_bank", "0001_baseline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("problems", "0001_baseline"),
    ]

    operations = [
        migrations.AddField(
            model_name="codingproblem",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_problems",
                to=settings.AUTH_USER_MODEL,
                verbose_name="建立者",
            ),
        ),
        migrations.AddField(
            model_name="codingproblem",
            name="question_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coding_problem_adapters",
                to="question_bank.questionasset",
                verbose_name="對應題目資產",
            ),
        ),
        migrations.AddField(
            model_name="codingproblem",
            name="question_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coding_problem_adapters",
                to="question_bank.questionversion",
                verbose_name="對應題目版本",
            ),
        ),
        migrations.AddField(
            model_name="codingproblem",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="problems",
                to="problems.tag",
                verbose_name="標籤",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="languageconfig",
            unique_together={("problem", "language")},
        ),
    ]
