# Generated by Django 4.2.26 on 2025-11-30 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0008_contest_is_ended"),
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="created_in_contest",
            field=models.ForeignKey(
                blank=True,
                help_text="記錄此題最初在哪場競賽中建立",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="originally_created_problems",
                to="contests.contest",
                verbose_name="來源競賽",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="is_practice_visible",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="控制此題是否在練習題庫中顯示給學生",
                verbose_name="顯示在練習題庫",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="contest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_contest_problems",
                to="contests.contest",
                verbose_name="所屬競賽 (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="is_contest_only",
            field=models.BooleanField(default=False, verbose_name="僅限競賽 (deprecated)"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="source_problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="problems.problem",
                verbose_name="來源題目 (deprecated)",
            ),
        ),
    ]
