# Generated by Django 4.2.26 on 2025-11-29 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("cpp", "C++"),
                            ("python", "Python"),
                            ("java", "Java"),
                            ("javascript", "JavaScript"),
                        ],
                        max_length=20,
                        verbose_name="程式語言",
                    ),
                ),
                (
                    "template_code",
                    models.TextField(blank=True, default="", verbose_name="範本程式碼"),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="啟用")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_configs",
                        to="problems.problem",
                        verbose_name="題目",
                    ),
                ),
            ],
            options={
                "verbose_name": "語言設定",
                "verbose_name_plural": "語言設定",
                "db_table": "problem_language_configs",
                "ordering": ["order", "language"],
                "unique_together": {("problem", "language")},
            },
        ),
    ]
