# Generated by Django 4.2.26 on 2025-11-30 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0003_migrate_practice_visibility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="contest",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="is_contest_only",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="source_problem",
        ),
    ]
