# Generated by Django 4.2.26 on 2025-11-29 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0006_contest_allow_multiple_joins_and_more"),
        ("problems", "0003_add_language_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="contest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contest_problems",
                to="contests.contest",
                verbose_name="所屬競賽",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="is_contest_only",
            field=models.BooleanField(default=False, verbose_name="僅限競賽"),
        ),
        migrations.AddField(
            model_name="problem",
            name="source_problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="problems.problem",
                verbose_name="來源題目",
            ),
        ),
    ]
