# Generated by Django 4.2.26 on 2025-12-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0004_remove_problem_contest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="標籤名稱"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "color",
                    models.CharField(
                        default="#0f62fe",
                        help_text="Hex color code for tag display",
                        max_length=7,
                        verbose_name="顏色",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "標籤",
                "verbose_name_plural": "標籤",
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="problem",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="problems",
                to="problems.tag",
                verbose_name="標籤",
            ),
        ),
    ]
