# Generated by Django 4.2.26 on 2025-11-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0004_problem_contest_problem_is_contest_only_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="display_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="顯示編號"
            ),
        ),
    ]
