# Generated by Django 4.2.27 on 2025-12-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0005_tag_problem_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="forbidden_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="提交代碼中不可出現的關鍵字列表 (substring match)",
                verbose_name="禁用關鍵字",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="required_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="提交代碼中必須包含的關鍵字列表 (substring match)",
                verbose_name="必須關鍵字",
            ),
        ),
    ]
