# Generated by Django 4.2.27 on 2026-01-03 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("problems", "0009_problem_discussions"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "評論按讚",
                "verbose_name_plural": "評論按讚",
                "db_table": "problem_discussion_comment_likes",
            },
        ),
        migrations.CreateModel(
            name="DiscussionLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "討論按讚",
                "verbose_name_plural": "討論按讚",
                "db_table": "problem_discussion_likes",
            },
        ),
        migrations.RenameIndex(
            model_name="problemdiscussion",
            new_name="problem_dis_problem_e3b58b_idx",
            old_name="problem_discussions_problem_created_idx",
        ),
        migrations.RenameIndex(
            model_name="problemdiscussion",
            new_name="problem_dis_user_id_03cc0d_idx",
            old_name="problem_discussions_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="problemdiscussioncomment",
            new_name="problem_dis_discuss_ea02e0_idx",
            old_name="problem_discussion_comments_discussion_created_idx",
        ),
        migrations.AlterField(
            model_name="problemdiscussion",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="problemdiscussioncomment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="discussionlike",
            name="discussion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="problems.problemdiscussion",
                verbose_name="討論",
            ),
        ),
        migrations.AddField(
            model_name="discussionlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussion_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="使用者",
            ),
        ),
        migrations.AddField(
            model_name="commentlike",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="problems.problemdiscussioncomment",
                verbose_name="評論",
            ),
        ),
        migrations.AddField(
            model_name="commentlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="使用者",
            ),
        ),
        migrations.AddIndex(
            model_name="discussionlike",
            index=models.Index(
                fields=["discussion"], name="problem_dis_discuss_d8e5c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussionlike",
            index=models.Index(fields=["user"], name="problem_dis_user_id_415b9d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="discussionlike",
            unique_together={("discussion", "user")},
        ),
        migrations.AddIndex(
            model_name="commentlike",
            index=models.Index(
                fields=["comment"], name="problem_dis_comment_9b28b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentlike",
            index=models.Index(fields=["user"], name="problem_dis_user_id_6bf081_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="commentlike",
            unique_together={("comment", "user")},
        ),
    ]
