# Generated by Django 4.2.27 on 2026-01-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0012_migrate_and_remove_old_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="problem",
            name="problems_is_visi_40a652_idx",
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["visibility"], name="problems_visibil_5c35f4_idx"
            ),
        ),
    ]
