# Generated by Django 4.2.30 on 2026-04-11 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0020_rename_problem_to_codingproblem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="discussionlike",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="discussionlike",
            name="discussion",
        ),
        migrations.RemoveField(
            model_name="discussionlike",
            name="user",
        ),
        migrations.RemoveField(
            model_name="problemdiscussion",
            name="problem",
        ),
        migrations.RemoveField(
            model_name="problemdiscussion",
            name="user",
        ),
        migrations.RemoveField(
            model_name="problemdiscussioncomment",
            name="discussion",
        ),
        migrations.RemoveField(
            model_name="problemdiscussioncomment",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="problemdiscussioncomment",
            name="user",
        ),
        migrations.DeleteModel(
            name="CommentLike",
        ),
        migrations.DeleteModel(
            name="DiscussionLike",
        ),
        migrations.DeleteModel(
            name="ProblemDiscussion",
        ),
        migrations.DeleteModel(
            name="ProblemDiscussionComment",
        ),
    ]
