# Generated by Django 4.2.30 on 2026-04-12 03:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0021_remove_discussion_models"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="problemtranslation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="problemtranslation",
            name="problem",
        ),
        migrations.RemoveIndex(
            model_name="codingproblem",
            name="problems_difficu_cbb392_idx",
        ),
        migrations.RemoveField(
            model_name="codingproblem",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="codingproblem",
            name="title",
        ),
        migrations.DeleteModel(
            name="ProblemTranslation",
        ),
    ]
