# Generated by Django 4.2.29 on 2026-04-07 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="收件信箱"),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("classroom_announcement", "教室公告"),
                            ("contest_announcement", "考場公告"),
                            ("grade_published", "成績公布"),
                            ("exam_reminder", "考試提醒"),
                        ],
                        max_length=50,
                        verbose_name="通知類型",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="信件主旨")),
                ("body_text", models.TextField(blank=True, verbose_name="純文字內容")),
                ("body_html", models.TextField(blank=True, verbose_name="HTML 內容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待寄送"),
                            ("queued", "已排入佇列"),
                            ("delivered", "已送達"),
                            ("failed", "失敗"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="重試次數"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="錯誤訊息")),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="來源 ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="寄送時間"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="來源類型",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="收件人",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="觸發者",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email 通知",
                "verbose_name_plural": "Email 通知",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["notification_type", "status"],
                        name="notificatio_notific_eb8b6c_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="notificatio_content_3ca5a9_idx",
                    ),
                ],
            },
        ),
    ]
