# Generated by Django 4.2.26 on 2025-11-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "系統通知"),
                            ("contest", "考試通知"),
                            ("submission", "評測通知"),
                            ("discussion", "討論通知"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="類型",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="標題")),
                ("message", models.TextField(verbose_name="內容")),
                (
                    "link",
                    models.CharField(blank=True, max_length=255, verbose_name="連結"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="已讀")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
