import React, { useState } from "react";
import { Modal, TextInput, Form, InlineNotification } from "@carbon/react";
import { useTranslation } from "react-i18next";
import { createProblem } from "@/infrastructure/api/repositories/problem.repository";

interface CreateProblemModalProps {
  open: boolean;
  onClose: () => void;
  onCreated: (problemId?: string) => void;
}

const CreateProblemModal: React.FC<CreateProblemModalProps> = ({
  open,
  onClose,
  onCreated,
}) => {
  const { t } = useTranslation("problem");
  const [title, setTitle] = useState("");
  const [slug, setSlug] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title) return;

    setLoading(true);
    setError("");

    try {
      const createdProblem = await createProblem({
        title,
        // slug: slug || undefined, // Slug is generated by backend or not in payload type
        difficulty: "medium", // Default
        time_limit: 1000,
        memory_limit: 128,
        translations: [],
      });
      onCreated(createdProblem.id);
      onClose();
      setTitle("");
      setSlug("");
    } catch (err: any) {
      setError(err.message || "Failed to create problem");
    } finally {
      setLoading(false);
    }
  };

  return (
    <Modal
      open={open}
      onRequestClose={onClose}
      modalHeading={t('page.createProblem')}
      primaryButtonText={t("button.create")}
      secondaryButtonText={t('button.cancel')}
      onRequestSubmit={handleSubmit}
      onSecondarySubmit={onClose}
      primaryButtonDisabled={!title || loading}
    >
      <Form onSubmit={handleSubmit}>
        {error && (
          <InlineNotification
            kind="error"
            title={t("common:error.title")}
            subtitle={error}
            style={{ marginBottom: "1rem" }}
          />
        )}
        <TextInput
          id="problem-title"
          labelText={t("form.title")}
          placeholder={t("form.placeholder.title")}
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          required
          style={{ marginBottom: "1rem" }}
        />
        <TextInput
          id="problem-slug"
          labelText={t("form.slug")}
          placeholder={t("form.placeholder.slug", "Optional: custom-slug")}
          value={slug}
          onChange={(e) => setSlug(e.target.value)}
          helperText={t("form.helper.slug", "Leave empty for auto-generated slug")}
        />
      </Form>
    </Modal>
  );
};

export default CreateProblemModal;
