# Generated by Django 4.2.29 on 2026-04-04 04:41

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    replaces = [
        ("users", "0001_initial"),
        ("users", "0002_add_user_preferences"),
        ("users", "0003_add_user_api_key"),
        (
            "users",
            "0004_rename_user_api_keys_user_idx_user_api_ke_user_id_42a3cd_idx_and_more",
        ),
        ("users", "0005_add_display_name_to_profile"),
        ("users", "0006_create_user_login_record"),
        ("users", "0007_create_user_login_record"),
        ("users", "0008_add_avatar_fields"),
        ("users", "0009_add_onboarding_completed_at"),
        ("users", "0010_create_teacher_activation_invites"),
    ]

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "A user with that email already exists."
                        },
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="email address",
                    ),
                ),
                (
                    "auth_provider",
                    models.CharField(
                        choices=[
                            ("email", "Email/Password"),
                            ("nycu-oauth", "NYCU OAuth"),
                            ("google", "Google"),
                            ("github", "GitHub"),
                        ],
                        db_index=True,
                        default="email",
                        max_length=20,
                        verbose_name="認證方式",
                    ),
                ),
                (
                    "oauth_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="OAuth ID",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, verbose_name="Email 已驗證"),
                ),
                (
                    "email_verification_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_verification_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "password_reset_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "password_reset_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "學生"),
                            ("teacher", "教師"),
                            ("admin", "管理員"),
                        ],
                        db_index=True,
                        default="student",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最後登入時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "使用者",
                "verbose_name_plural": "使用者",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solved_count", models.IntegerField(default=0, verbose_name="已解題數")),
                (
                    "submission_count",
                    models.IntegerField(default=0, verbose_name="提交次數"),
                ),
                (
                    "accept_rate",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=5, verbose_name="通過率"
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="zh-hant", max_length=20, verbose_name="偏好語言"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "使用者資料",
                "verbose_name_plural": "使用者資料",
                "db_table": "user_profiles",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["auth_provider", "oauth_id"], name="users_auth_pr_e717fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("auth_provider", "email"), ("password", ""), _negated=True
                    ),
                    models.Q(("auth_provider", "email"), ("password__isnull", False)),
                    _connector="OR",
                ),
                name="email_users_must_have_password",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="editor_font_size",
            field=models.IntegerField(default=14, verbose_name="編輯器字體大小"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="editor_tab_size",
            field=models.IntegerField(
                choices=[(2, "2 spaces"), (4, "4 spaces")],
                default=4,
                verbose_name="Tab 寬度",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                default="system",
                max_length=10,
                verbose_name="偏好主題",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(default="zh-TW", max_length=20, verbose_name="偏好語言"),
        ),
        migrations.CreateModel(
            name="UserAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_key", models.BinaryField(verbose_name="加密的 API Key")),
                (
                    "key_name",
                    models.CharField(
                        default="My API Key", max_length=100, verbose_name="API Key 名稱"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否啟用")),
                (
                    "is_validated",
                    models.BooleanField(default=False, verbose_name="是否已驗證"),
                ),
                (
                    "last_validated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最後驗證時間"),
                ),
                (
                    "total_input_tokens",
                    models.BigIntegerField(default=0, verbose_name="總輸入 Token 數"),
                ),
                (
                    "total_output_tokens",
                    models.BigIntegerField(default=0, verbose_name="總輸出 Token 數"),
                ),
                (
                    "total_requests",
                    models.IntegerField(default=0, verbose_name="總請求次數"),
                ),
                (
                    "total_cost_cents",
                    models.BigIntegerField(
                        default=0, help_text="以美分表示，避免浮點精度問題", verbose_name="總費用（美分）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_key",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "使用者 API Key",
                "verbose_name_plural": "使用者 API Keys",
                "db_table": "user_api_keys",
                "indexes": [
                    models.Index(
                        fields=["user"], name="user_api_ke_user_id_42a3cd_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="user_api_ke_is_acti_be78f3_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="顯示名稱"
            ),
        ),
        migrations.CreateModel(
            name="UserLoginRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(blank=True, default="", max_length=128)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("login_method", models.CharField(max_length=32)),
                ("jti", models.CharField(blank=True, default="", max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_login_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="user_login__user_id_af7c24_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("oauth", "OAuth")],
                default="manual",
                max_length=20,
                verbose_name="頭像來源",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(
                blank=True, default="", max_length=500, null=True, verbose_name="頭像 URL"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="完成 onboarding 時間"
            ),
        ),
        migrations.CreateModel(
            name="TeacherActivationInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="邀請 Email",
                    ),
                ),
                (
                    "token_digest",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Token 雜湊",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="過期時間")),
                (
                    "consumed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="使用時間"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "consumed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumed_teacher_activation_invites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_teacher_activation_invites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="建立者",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_activation_invites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="目標使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "教師開通邀請",
                "verbose_name_plural": "教師開通邀請",
                "db_table": "teacher_activation_invites",
                "indexes": [
                    models.Index(fields=["email"], name="teacher_act_email_9fee36_idx"),
                    models.Index(
                        fields=["expires_at"], name="teacher_act_expires_7cad22_idx"
                    ),
                ],
            },
        ),
    ]
