# Generated by Django 4.2.27 on 2025-12-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="editor_font_size",
            field=models.IntegerField(default=14, verbose_name="編輯器字體大小"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="editor_tab_size",
            field=models.IntegerField(
                choices=[(2, "2 spaces"), (4, "4 spaces")],
                default=4,
                verbose_name="Tab 寬度",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                default="system",
                max_length=10,
                verbose_name="偏好主題",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(default="zh-TW", max_length=20, verbose_name="偏好語言"),
        ),
    ]
