# Generated by Django 4.2.30 on 2026-04-15 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_fix_preferred_language_choices"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserAPIKey",
        ),
    ]
