# Generated by Codex on 2026-06-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_delete_userapikey"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_key",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="Provider Key",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=255,
                        verbose_name="Provider Subject",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=254,
                        verbose_name="Provider Email",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        verbose_name="Provider Email 已驗證",
                    ),
                ),
                (
                    "profile_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Provider Profile Snapshot",
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="最後登入時間",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="建立時間",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="更新時間",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "外部身份",
                "verbose_name_plural": "外部身份",
                "db_table": "external_identities",
            },
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                fields=("provider_key", "subject"),
                name="unique_external_identity_provider_subject",
            ),
        ),
        migrations.AddIndex(
            model_name="externalidentity",
            index=models.Index(
                fields=["user", "provider_key"],
                name="external_id_user_id_94d6ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="externalidentity",
            index=models.Index(
                fields=["provider_key", "email"],
                name="external_id_provide_d58c14_idx",
            ),
        ),
    ]
