# Generated by Django 4.2.28 on 2026-02-25 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_add_user_api_key"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userapikey",
            new_name="user_api_ke_user_id_42a3cd_idx",
            old_name="user_api_keys_user_idx",
        ),
        migrations.RenameIndex(
            model_name="userapikey",
            new_name="user_api_ke_is_acti_be78f3_idx",
            old_name="user_api_keys_is_active_idx",
        ),
    ]
