# Generated by Django 4.2.29 on 2026-03-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0004_rename_user_api_keys_user_idx_user_api_ke_user_id_42a3cd_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="顯示名稱"
            ),
        ),
    ]
