# Generated by Django 4.2.30 on 2026-07-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_converge_nycu_provider_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("email", "Password credentials"),
                    ("nycu", "NYCU OAuth"),
                    ("google", "Google"),
                    ("github", "GitHub"),
                ],
                db_index=True,
                default="email",
                max_length=20,
                verbose_name="認證方式",
            ),
        ),
    ]
