# Generated by Django 4.2.30 on 2026-07-06 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_auth_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password_reset_expires_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password_reset_token",
        ),
    ]
