# Generated by Django 4.2.29 on 2026-03-19 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_create_user_login_record"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userloginrecord",
            new_name="user_login__user_id_af7c24_idx",
            old_name="user_login_r_user_id_created_idx",
        ),
    ]
