# Generated by Django 4.2.29 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_create_user_login_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("oauth", "OAuth")],
                default="manual",
                max_length=20,
                verbose_name="頭像來源",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=500,
                null=True,
                verbose_name="頭像 URL",
            ),
        ),
    ]
