# Generated by Django 4.2.30 on 2026-07-13 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def _backfill_classroom_uuid(apps, schema_editor):
    Classroom = apps.get_model("classrooms", "Classroom")
    for classroom in Classroom.objects.filter(uuid__isnull=True).iterator(chunk_size=200):
        classroom.uuid = uuid.uuid4()
        classroom.save(update_fields=["uuid"])


def cleanup_reserved_memberships(apps, schema_editor):
    Classroom = apps.get_model("classrooms", "Classroom")
    ClassroomMember = apps.get_model("classrooms", "ClassroomMember")
    through_model = Classroom.admins.through

    reserved_user_ids_by_classroom = {}
    for classroom_id, owner_id in Classroom.objects.values_list("id", "owner_id"):
        reserved_user_ids_by_classroom[classroom_id] = {owner_id}
    for classroom_id, user_id in through_model.objects.values_list("classroom_id", "user_id"):
        reserved_user_ids_by_classroom.setdefault(classroom_id, set()).add(user_id)

    for classroom_id, reserved_user_ids in reserved_user_ids_by_classroom.items():
        ClassroomMember.objects.filter(
            classroom_id=classroom_id,
            user_id__in=reserved_user_ids,
        ).delete()


class Migration(migrations.Migration):

    initial = True

    replaces = [('classrooms', '0001_initial'), ('classrooms', '0002_delete_classroomlab'), ('classrooms', '0003_classroomannouncement'), ('classrooms', '0004_classroom_uuid'), ('classrooms', '0005_classroom_icon_cover_url'), ('classrooms', '0006_alter_classroom_icon'), ('classrooms', '0007_cleanup_reserved_memberships'), ('classrooms', '0008_drop_legacy_email_notifications')]

    dependencies = [
        ('contests', '0032_add_exam_answer_and_results_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('invite_code', models.CharField(max_length=8, unique=True, verbose_name='邀請碼')),
                ('invite_code_enabled', models.BooleanField(default=True, verbose_name='邀請碼啟用')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='已封存')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='管理員')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('ta', 'TA')], default='student', max_length=10, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='classrooms.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('classroom', 'user')},
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='members',
            field=models.ManyToManyField(related_name='joined_classrooms', through='classrooms.ClassroomMember', to=settings.AUTH_USER_MODEL, verbose_name='成員'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='擁有者'),
        ),
        migrations.CreateModel(
            name='ClassroomContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bound_at', models.DateTimeField(auto_now_add=True, verbose_name='綁定時間')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_contests', to='classrooms.classroom')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_bindings', to='contests.contest')),
            ],
            options={
                'unique_together': {('classroom', 'contest')},
            },
        ),
        migrations.CreateModel(
            name='ClassroomAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置頂')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='發布時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classrooms.classroom', verbose_name='教室')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classroom_announcements', to=settings.AUTH_USER_MODEL, verbose_name='發布者')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True, verbose_name='UUID'),
        ),
        migrations.RunPython(
            code=_backfill_classroom_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='cover_url',
            field=models.URLField(blank=True, default='', verbose_name='封面圖片 URL'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='圖示'),
        ),
        migrations.RunPython(
            code=cleanup_reserved_memberships,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "notifications_emailnotification" CASCADE',
            reverse_sql='',
        ),
    ]
