# Generated by Django 4.2.28 on 2026-02-26 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("labs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contests", "0032_add_exam_answer_and_results_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名稱")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "invite_code",
                    models.CharField(max_length=8, unique=True, verbose_name="邀請碼"),
                ),
                (
                    "invite_code_enabled",
                    models.BooleanField(default=True, verbose_name="邀請碼啟用"),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="已封存"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="admin_classrooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="管理員",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassroomMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Student"), ("ta", "TA")],
                        default="student",
                        max_length=10,
                        verbose_name="角色",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入時間"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="classrooms.classroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("classroom", "user")},
            },
        ),
        migrations.AddField(
            model_name="classroom",
            name="members",
            field=models.ManyToManyField(
                related_name="joined_classrooms",
                through="classrooms.ClassroomMember",
                to=settings.AUTH_USER_MODEL,
                verbose_name="成員",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_classrooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="擁有者",
            ),
        ),
        migrations.CreateModel(
            name="ClassroomLab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bound_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="綁定時間"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_labs",
                        to="classrooms.classroom",
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_bindings",
                        to="labs.lab",
                    ),
                ),
            ],
            options={
                "unique_together": {("classroom", "lab")},
            },
        ),
        migrations.CreateModel(
            name="ClassroomContest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bound_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="綁定時間"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_contests",
                        to="classrooms.classroom",
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_bindings",
                        to="contests.contest",
                    ),
                ),
            ],
            options={
                "unique_together": {("classroom", "contest")},
            },
        ),
    ]
