# Generated by Django 4.2.30 on 2026-09-15 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classrooms", "0001_baseline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contests", "0002_baseline"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroommember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classroomcontest",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_contests",
                to="classrooms.classroom",
            ),
        ),
        migrations.AddField(
            model_name="classroomcontest",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_bindings",
                to="contests.contest",
            ),
        ),
        migrations.AddField(
            model_name="classroomannouncement",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="classrooms.classroom",
                verbose_name="教室",
            ),
        ),
        migrations.AddField(
            model_name="classroomannouncement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_classroom_announcements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="發布者",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="admin_classrooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="管理員",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="members",
            field=models.ManyToManyField(
                related_name="joined_classrooms",
                through="classrooms.ClassroomMember",
                to=settings.AUTH_USER_MODEL,
                verbose_name="成員",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_classrooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="擁有者",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classroommember",
            unique_together={("classroom", "user")},
        ),
        migrations.AddConstraint(
            model_name="classroomcontest",
            constraint=models.UniqueConstraint(
                fields=("contest",), name="unique_classroom_binding_per_contest"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classroomcontest",
            unique_together={("classroom", "contest")},
        ),
    ]
