# Generated by Django 4.2.28 on 2026-02-26 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classrooms", "0002_delete_classroomlab"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassroomAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="標題")),
                ("content", models.TextField(verbose_name="內容")),
                ("is_pinned", models.BooleanField(default=False, verbose_name="置頂")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="發布時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="classrooms.classroom",
                        verbose_name="教室",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_classroom_announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="發布者",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
    ]
