"""Contest exporters package public API."""

from .renderers import (
    BaseRenderer,
    MarkdownRenderer,
    PDFRenderer,
    StudentReportRenderer,
    PaperExamReportRenderer,
    PaperExamSheetRenderer,
)
from .data_service import ContestDataService
from .dto import (
    ContestDTO,
    ContestProblemDTO,
    ProblemDTO,
    SampleCaseDTO,
    ParticipantDTO,
    SubmissionDTO,
    StandingsDTO,
    UserStandingDTO,
    ProblemStatsDTO,
    DifficultyStatsDTO,
)
from .locales import get_labels, validate_labels, is_chinese, REQUIRED_KEYS
from .utils import (
    sanitize_filename,
    render_markdown,
    inline_markdown,
    preprocess_markdown_html,
    ensure_markdown_lists,
    highlight_code,
    CHART_COLORS,
    get_chart_color,
    generate_donut_chart_svg,
    generate_empty_chart_svg,
    get_carbon_code_styles,
)

__all__ = [
    "BaseRenderer",
    "MarkdownRenderer",
    "PDFRenderer",
    "StudentReportRenderer",
    "PaperExamReportRenderer",
    "PaperExamSheetRenderer",
    "ContestDataService",
    "ContestDTO",
    "ContestProblemDTO",
    "ProblemDTO",
    "SampleCaseDTO",
    "ParticipantDTO",
    "SubmissionDTO",
    "StandingsDTO",
    "UserStandingDTO",
    "ProblemStatsDTO",
    "DifficultyStatsDTO",
    "get_labels",
    "validate_labels",
    "is_chinese",
    "REQUIRED_KEYS",
    "sanitize_filename",
    "render_markdown",
    "inline_markdown",
    "preprocess_markdown_html",
    "ensure_markdown_lists",
    "highlight_code",
    "CHART_COLORS",
    "get_chart_color",
    "generate_donut_chart_svg",
    "generate_empty_chart_svg",
    "get_carbon_code_styles",
]
