# Generated by Django 4.2.30 on 2026-09-15 08:43

import apps.contests.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clarification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="問題")),
                ("answer", models.TextField(blank=True, null=True, verbose_name="回答")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="是否對所有參賽者公開此 Q&A", verbose_name="公開"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("answered", "Answered")],
                        default="pending",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提問時間"),
                ),
                (
                    "answered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="回答時間"),
                ),
            ],
            options={
                "verbose_name": "Clarification",
                "verbose_name_plural": "Clarifications",
                "db_table": "contest_clarifications",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="名稱"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("rules", models.TextField(blank=True, verbose_name="競賽規定")),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="開始時間"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="結束時間"),
                ),
                ("schedule_revision", models.PositiveIntegerField(default=1)),
                (
                    "attendance_check_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="啟用後學生需先完成 QR 簽到與現場照片佐證才可開始考試",
                        verbose_name="啟用 QR 簽到簽退",
                    ),
                ),
                (
                    "attendance_photo_policy",
                    models.CharField(
                        choices=[
                            ("room", "Room photo"),
                            ("room_and_selfie", "Room and selfie photos"),
                        ],
                        default="room",
                        help_text="room: 後鏡頭拍攝現場; room_and_selfie: 後鏡頭現場與前鏡頭本人各一張",
                        max_length=24,
                        verbose_name="簽到佐證照片策略",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="draft: 草稿未發布；published: 已發布可進行；archived: 已封存唯讀",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "allow_multiple_joins",
                    models.BooleanField(default=False, verbose_name="允許多次加入"),
                ),
                (
                    "contest_type",
                    models.CharField(
                        choices=[
                            ("coding", "Coding Test"),
                            ("paper_exam", "Paper Exam"),
                        ],
                        default="coding",
                        help_text="coding: 程式題; paper_exam: 紙筆題考試",
                        max_length=15,
                        verbose_name="比賽類型",
                    ),
                ),
                (
                    "cheat_detection_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="啟用全螢幕與防失焦的嚴格防作弊模式",
                        verbose_name="啟用防作弊模式",
                    ),
                ),
                (
                    "anticheat_device_policy",
                    models.JSONField(
                        default=apps.contests.models.default_anticheat_device_policy,
                        help_text="依裝置定義 sources/detectors 的監考策略",
                        verbose_name="防作弊裝置策略",
                    ),
                ),
                (
                    "scoreboard_visible_during_contest",
                    models.BooleanField(
                        default=False,
                        help_text="False: 學生只能看自己成績；True: 學生可看完整排行榜",
                        verbose_name="比賽中顯示排行榜",
                    ),
                ),
                (
                    "results_published",
                    models.BooleanField(
                        default=False,
                        help_text="TA 完成批改後手動設為 True，學生才能查看成績",
                        verbose_name="成績已公布",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "考試",
                "verbose_name_plural": "考試",
                "db_table": "contests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContestActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("register", "Register"),
                            ("enter_contest", "Enter Contest"),
                            ("start_exam", "Start Exam"),
                            ("resume_exam", "Resume Exam"),
                            ("end_exam", "End Exam"),
                            ("auto_submit", "Auto Submit"),
                            ("lock_user", "Lock User"),
                            ("unlock_user", "Unlock User"),
                            ("submit_code", "Submit Code"),
                            ("ask_question", "Ask Question"),
                            ("reply_question", "Reply Question"),
                            ("update_contest", "Update Contest"),
                            ("update_problem", "Update Problem"),
                            ("update_participant", "Update Participant"),
                            ("reopen_exam", "Reopen Exam"),
                            ("reset_exam_record", "Reset Exam Record"),
                            ("concurrent_login_detected", "Concurrent Login Detected"),
                            ("other_devices_logged_out", "Other Devices Logged Out"),
                            ("announce", "Announce"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="動作類型",
                    ),
                ),
                ("details", models.TextField(verbose_name="詳細內容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="發生時間"),
                ),
            ],
            options={
                "verbose_name": "競賽活動",
                "verbose_name_plural": "競賽活動",
                "db_table": "contest_activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContestAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="標題")),
                ("content", models.TextField(verbose_name="內容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="發布時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "考試公告",
                "verbose_name_plural": "考試公告",
                "db_table": "contest_announcements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContestParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="總分"
                    ),
                ),
                ("rank", models.IntegerField(blank=True, null=True, verbose_name="排名")),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入時間"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="開始時間"),
                ),
                (
                    "left_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="離開時間"),
                ),
                (
                    "integrity_attempt_id",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "locked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="鎖定時間"),
                ),
                ("lock_reason", models.TextField(blank=True, verbose_name="鎖定原因")),
                (
                    "violation_count",
                    models.IntegerField(default=0, verbose_name="違規次數"),
                ),
                (
                    "submit_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="手動或系統自動交卷原因",
                        verbose_name="交卷原因",
                    ),
                ),
                (
                    "exam_status",
                    models.CharField(
                        choices=[
                            ("not_started", "未開始"),
                            ("in_progress", "進行中"),
                            ("paused", "暫停"),
                            ("locked", "已鎖定"),
                            ("submitted", "已交卷"),
                        ],
                        default="not_started",
                        help_text="學生考試狀態：未開始/進行中/暫停/已鎖定/已交卷",
                        max_length=20,
                        verbose_name="考試狀態",
                    ),
                ),
            ],
            options={
                "verbose_name": "考試參與者",
                "verbose_name_plural": "考試參與者",
                "db_table": "contest_participants",
            },
        ),
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='選擇題: {"selected": "A"}, 多選: {"selected": ["A","B"]}, 簡答/問答: {"text": "..."}',
                        verbose_name="作答內容",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True,
                        help_text="選擇/是非題自動判定；問答題由 TA 手動設定",
                        null=True,
                        verbose_name="是否正確",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="得分",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="批改評語")),
                (
                    "graded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="批改時間"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "考試作答",
                "verbose_name_plural": "考試作答",
                "db_table": "exam_answers",
            },
        ),
        migrations.CreateModel(
            name="ExamEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=64, verbose_name="事件類型")),
                (
                    "integrity_command_id",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                ("incident_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "event_definition_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("event_schema_version", models.PositiveIntegerField(default=1)),
                (
                    "client_occurred_at_ms",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("server_received_at", models.DateTimeField(blank=True, null=True)),
                ("worker_processed_at", models.DateTimeField(blank=True, null=True)),
                ("delayed_delivery", models.BooleanField(default=False)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="JSON 格式的額外事件資訊",
                        null=True,
                        verbose_name="額外資訊",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="發生時間"),
                ),
            ],
            options={
                "verbose_name": "考試事件",
                "verbose_name_plural": "考試事件",
                "db_table": "exam_events",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamEvidenceChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("incident_id", models.UUIDField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("screen_share", "Screen share"),
                            ("webcam", "Webcam"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recording_session_id", models.UUIDField()),
                ("chunk_seq", models.PositiveIntegerField()),
                ("is_init_chunk", models.BooleanField(default=False)),
                ("start_at_ms", models.BigIntegerField()),
                ("end_at_ms", models.BigIntegerField()),
                ("object_key", models.TextField()),
                ("content_type", models.CharField(max_length=96)),
                ("codec", models.CharField(blank=True, default="", max_length=96)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "previous_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("uploaded", "Uploaded"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "exam_evidence_chunks",
            },
        ),
        migrations.CreateModel(
            name="ExamEvidenceFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_cluster_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "source_module",
                    models.CharField(
                        choices=[
                            ("screen_share", "Screen Share"),
                            ("webcam", "Webcam"),
                            ("attendance", "Attendance"),
                        ],
                        default="screen_share",
                        max_length=20,
                    ),
                ),
                (
                    "capture_origin",
                    models.CharField(
                        choices=[("student_local", "Student Local")],
                        default="student_local",
                        max_length=32,
                    ),
                ),
                (
                    "evidence_mode",
                    models.CharField(
                        choices=[
                            ("anchor_window", "Anchor Window"),
                            ("pre_loss", "Pre Loss"),
                            ("audit", "Audit"),
                        ],
                        default="anchor_window",
                        max_length=20,
                    ),
                ),
                (
                    "upload_session_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("seq", models.PositiveIntegerField(default=0)),
                ("object_key", models.TextField(blank=True, default="")),
                (
                    "client_captured_at_ms",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("server_issued_at", models.DateTimeField(auto_now_add=True)),
                ("storage_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("uploaded", "Uploaded"),
                            ("failed", "Failed"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("content_type", models.CharField(default="image/webp", max_length=64)),
                ("byte_size", models.PositiveIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "考試證據影格",
                "verbose_name_plural": "考試證據影格",
                "db_table": "exam_evidence_frames",
                "ordering": ["client_captured_at_ms", "seq", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExamIntegrityRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_state",
                    models.CharField(
                        choices=[
                            ("prepared", "Prepared"),
                            ("active", "Active"),
                            ("draining", "Draining"),
                            ("archived", "Archived"),
                            ("closed", "Closed"),
                        ],
                        default="prepared",
                        max_length=16,
                    ),
                ),
                ("schedule_revision", models.PositiveIntegerField(default=1)),
                ("accept_until", models.DateTimeField(blank=True, null=True)),
                (
                    "health",
                    models.CharField(
                        choices=[("healthy", "Healthy"), ("unhealthy", "Unhealthy")],
                        default="healthy",
                        max_length=16,
                    ),
                ),
                (
                    "data_state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("archived", "Archived"),
                            ("purged", "Purged"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "last_correlation_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("policy_snapshot", models.JSONField(default=dict)),
                ("registry_snapshot", models.JSONField(default=dict)),
                ("registry_version", models.CharField(max_length=64)),
                (
                    "worker_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("archive_generation", models.PositiveIntegerField(default=0)),
                ("archive_manifest_key", models.TextField(blank=True, default="")),
                (
                    "archive_manifest_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("received_counts", models.JSONField(blank=True, default=dict)),
                ("processed_counts", models.JSONField(blank=True, default=dict)),
                ("archived_counts", models.JSONField(blank=True, default=dict)),
                (
                    "last_worker_heartbeat_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("scheduled_start_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("destroyed_at", models.DateTimeField(blank=True, null=True)),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                ("retention_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "exam_integrity_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrityUploadGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=128)),
                ("attempt_id", models.UUIDField()),
                ("submitted_at", models.DateTimeField()),
                ("accept_until", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("final_seq", models.PositiveBigIntegerField(blank=True, null=True)),
                ("received_seq", models.PositiveBigIntegerField(default=0)),
                ("processed_seq", models.PositiveBigIntegerField(default=0)),
                ("commands_drained", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contests.contestparticipant",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contests.examintegrityrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrityBatchAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.UUIDField()),
                ("attempt_id", models.UUIDField()),
                ("device_id", models.CharField(max_length=128)),
                ("body_sha256", models.CharField(max_length=64)),
                ("first_seq", models.PositiveBigIntegerField()),
                ("last_seq", models.PositiveBigIntegerField()),
                ("first_received_at", models.DateTimeField()),
                ("late_unverified", models.BooleanField(default=False)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contests.contestparticipant",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contests.examintegrityrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamQuestionGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="題組標題"
                    ),
                ),
                (
                    "shared_stem_markdown",
                    models.TextField(blank=True, default="", verbose_name="共同題幹"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_question_groups",
                        to="contests.contest",
                        verbose_name="考試",
                    ),
                ),
            ],
            options={
                "verbose_name": "考卷題組",
                "verbose_name_plural": "考卷題組",
                "db_table": "exam_question_groups",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("true_false", "是非題"),
                            ("single_choice", "單選題"),
                            ("multiple_choice", "多選題"),
                            ("short_answer", "簡答題"),
                            ("essay", "問答題"),
                        ],
                        default="single_choice",
                        max_length=30,
                        verbose_name="題型",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="題目內容")),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="選擇題選項，陣列格式",
                        verbose_name="選項",
                    ),
                ),
                (
                    "correct_answer",
                    models.JSONField(
                        blank=True,
                        help_text="是非/選擇題可存標準答案，問答題可留空",
                        null=True,
                        verbose_name="標準答案",
                    ),
                ),
                (
                    "reference_answer_document",
                    models.JSONField(
                        blank=True,
                        help_text="open_document 題型使用的結構化評分參考答案",
                        null=True,
                        verbose_name="評分參考答案文件",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="題目詳解，於成績公布後提供學生查看",
                        verbose_name="詳解",
                    ),
                ),
                (
                    "explanation_document",
                    models.JSONField(
                        blank=True,
                        help_text="open_document 題型使用的結構化詳解",
                        null=True,
                        verbose_name="詳解文件",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=1, verbose_name="配分")),
                (
                    "score_policy",
                    models.CharField(
                        choices=[
                            ("normal", "正常計分"),
                            ("excluded", "不計分"),
                            ("full_marks", "送分"),
                            ("redistribute", "配分重分配"),
                        ],
                        default="normal",
                        help_text="normal=正常計分, excluded=不計分, full_marks=送分, redistribute=配分重分配",
                        max_length=16,
                        verbose_name="計分策略",
                    ),
                ),
                (
                    "score_policy_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='redistribute 模式使用：{"redistribute_to": ["question_uuid1", ...]}，空陣列表示全選',
                        verbose_name="計分策略設定",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "order_in_group",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="題組內排序"
                    ),
                ),
                (
                    "answer_format",
                    models.CharField(
                        choices=[
                            ("plain_text", "純文字"),
                            ("markdown", "Markdown"),
                            ("markdown_math", "Markdown + 數學式"),
                            ("open_document", "開放作答紙"),
                        ],
                        default="plain_text",
                        max_length=32,
                        verbose_name="答案格式",
                    ),
                ),
                (
                    "source_bank_id",
                    models.UUIDField(blank=True, null=True, verbose_name="來源題庫 UUID"),
                ),
                (
                    "source_bank_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="來源題庫名稱"
                    ),
                ),
                (
                    "source_question_id",
                    models.UUIDField(blank=True, null=True, verbose_name="來源題庫題目 UUID"),
                ),
                (
                    "source_mode",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("json", "JSON"),
                            ("copy", "Copy"),
                            ("reference", "Reference"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="來源模式",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_questions",
                        to="contests.contest",
                        verbose_name="考試",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="contests.examquestiongroup",
                        verbose_name="題組",
                    ),
                ),
            ],
            options={
                "verbose_name": "考卷題目",
                "verbose_name_plural": "考卷題目",
                "db_table": "exam_questions",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
