# Generated by Django 4.2.26 on 2025-11-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="標題")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("start_time", models.DateTimeField(verbose_name="開始時間")),
                ("end_time", models.DateTimeField(verbose_name="結束時間")),
                ("is_visible", models.BooleanField(default=True, verbose_name="是否可見")),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公開")),
                (
                    "allow_view_results",
                    models.BooleanField(default=True, verbose_name="允許查看結果"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "考試",
                "verbose_name_plural": "考試",
                "db_table": "contests",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ContestParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="總分")),
                ("rank", models.IntegerField(blank=True, null=True, verbose_name="排名")),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入時間"),
                ),
            ],
            options={
                "verbose_name": "考試參與者",
                "verbose_name_plural": "考試參與者",
                "db_table": "contest_participants",
            },
        ),
        migrations.CreateModel(
            name="ContestProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                ("score", models.IntegerField(default=100, verbose_name="分數")),
            ],
            options={
                "verbose_name": "考試題目",
                "verbose_name_plural": "考試題目",
                "db_table": "contest_problems",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ContestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="標題")),
                ("content", models.TextField(verbose_name="內容")),
                ("reply", models.TextField(blank=True, verbose_name="回覆")),
                (
                    "replied_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="回覆時間"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提問時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="contests.contest",
                        verbose_name="考試",
                    ),
                ),
            ],
            options={
                "verbose_name": "考試提問",
                "verbose_name_plural": "考試提問",
                "db_table": "contest_questions",
                "ordering": ["created_at"],
            },
        ),
    ]
