# Generated by Django 4.2.30 on 2026-09-15 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("question_bank", "0001_baseline"),
        ("contests", "0001_baseline"),
    ]

    operations = [
        migrations.AddField(
            model_name="examquestion",
            name="question_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_question_adapters",
                to="question_bank.questionasset",
                verbose_name="對應題目資產",
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="question_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_question_adapters",
                to="question_bank.questionversion",
                verbose_name="對應題目版本",
            ),
        ),
        migrations.AddField(
            model_name="examintegrityrun",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrity_runs",
                to="contests.contest",
            ),
        ),
    ]
