# Generated by Django 4.2.26 on 2025-11-26 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contests", "0001_initial"),
        ("problems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contestquestion",
            name="replied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replied_questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="回覆者",
            ),
        ),
        migrations.AddField(
            model_name="contestquestion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contest_questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="提問者",
            ),
        ),
        migrations.AddField(
            model_name="contestproblem",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contests.contest"
            ),
        ),
        migrations.AddField(
            model_name="contestproblem",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="problems.problem"
            ),
        ),
        migrations.AddField(
            model_name="contestparticipant",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contests.contest"
            ),
        ),
        migrations.AddField(
            model_name="contestparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_contests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="建立者",
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="participants",
            field=models.ManyToManyField(
                related_name="participated_contests",
                through="contests.ContestParticipant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="參與者",
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="problems",
            field=models.ManyToManyField(
                related_name="contests",
                through="contests.ContestProblem",
                to="problems.problem",
                verbose_name="題目",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contestproblem",
            unique_together={("contest", "problem")},
        ),
        migrations.AlterUniqueTogether(
            name="contestparticipant",
            unique_together={("contest", "user")},
        ),
    ]
