# Generated by Django 4.2.26 on 2025-11-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="password",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="密碼"
            ),
        ),
        migrations.AddField(
            model_name="contestparticipant",
            name="left_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="離開時間"),
        ),
    ]
