from django.db import migrations

from apps.core.legacy_schema_alignment import build_alignment

# Catalog produced by the baseline migrations on an empty PostgreSQL database.
EXPECTED_CONSTRAINTS = (
    ("contest_activities", "contest_activities_contest_id_f2180fd0_fk_contests_id", "f", "FOREIGN KEY (contest_id) REFERENCES contests(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contest_activities", "contest_activities_pkey", "p", "PRIMARY KEY (id)"),
    ("contest_activities", "contest_activities_user_id_bf577cad_fk_users_id", "f", "FOREIGN KEY (user_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contest_announcements", "contest_announcements_contest_id_575ee8cf_fk_contests_id", "f", "FOREIGN KEY (contest_id) REFERENCES contests(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contest_announcements", "contest_announcements_created_by_id_aec9de9b_fk_users_id", "f", "FOREIGN KEY (created_by_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contest_announcements", "contest_announcements_pkey", "p", "PRIMARY KEY (id)"),
    ("contest_clarifications", "contest_clarifications_author_id_af151407_fk_users_id", "f", "FOREIGN KEY (author_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contest_clarifications", "contest_clarifications_contest_id_25da9663_fk_contests_id", "f", "FOREIGN KEY (contest_id) REFERENCES contests(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contest_clarifications", "contest_clarifications_pkey", "p", "PRIMARY KEY (id)"),
    ("contest_clarifications", "contest_clarifications_problem_id_1f7effed_fk_problems_id", "f", "FOREIGN KEY (problem_id) REFERENCES problems(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contest_participants", "contest_participants_contest_id_09eb8fd9_fk_contests_id", "f", "FOREIGN KEY (contest_id) REFERENCES contests(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contest_participants", "contest_participants_contest_id_user_id_fba0cd52_uniq", "u", "UNIQUE (contest_id, user_id)"),
    ("contest_participants", "contest_participants_pkey", "p", "PRIMARY KEY (id)"),
    ("contest_participants", "contest_participants_user_id_dd24a4e2_fk_users_id", "f", "FOREIGN KEY (user_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contests", "contests_owner_id_c57994d2_fk_users_id", "f", "FOREIGN KEY (owner_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contests", "contests_pkey", "p", "PRIMARY KEY (id)"),
    ("contests", "contests_schedule_revision_check", "c", "CHECK ((schedule_revision >= 0))"),
    ("contests_admins", "contests_admins_contest_id_184139c3_fk_contests_id", "f", "FOREIGN KEY (contest_id) REFERENCES contests(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contests_admins", "contests_admins_contest_id_user_id_2f699329_uniq", "u", "UNIQUE (contest_id, user_id)"),
    ("contests_admins", "contests_admins_pkey", "p", "PRIMARY KEY (id)"),
    ("contests_admins", "contests_admins_user_id_cdee87cf_fk_users_id", "f", "FOREIGN KEY (user_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contests_integritybatchadmission", "contests_integrityba_participant_id_9f271d22_fk_contest_p", "f", "FOREIGN KEY (participant_id) REFERENCES contest_participants(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contests_integritybatchadmission", "contests_integrityba_run_id_ac53460e_fk_exam_inte", "f", "FOREIGN KEY (run_id) REFERENCES exam_integrity_runs(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contests_integritybatchadmission", "contests_integritybatchadmission_first_seq_check", "c", "CHECK ((first_seq >= 0))"),
    ("contests_integritybatchadmission", "contests_integritybatchadmission_last_seq_check", "c", "CHECK ((last_seq >= 0))"),
    ("contests_integritybatchadmission", "contests_integritybatchadmission_pkey", "p", "PRIMARY KEY (id)"),
    ("contests_integritybatchadmission", "uniq_integrity_batch_admission", "u", "UNIQUE (run_id, batch_id)"),
    ("contests_integrityuploadgrant", "contests_integrityup_participant_id_3d7fef42_fk_contest_p", "f", "FOREIGN KEY (participant_id) REFERENCES contest_participants(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contests_integrityuploadgrant", "contests_integrityup_run_id_22c17d52_fk_exam_inte", "f", "FOREIGN KEY (run_id) REFERENCES exam_integrity_runs(id) DEFERRABLE INITIALLY DEFERRED"),
    ("contests_integrityuploadgrant", "contests_integrityuploadgrant_final_seq_check", "c", "CHECK ((final_seq >= 0))"),
    ("contests_integrityuploadgrant", "contests_integrityuploadgrant_pkey", "p", "PRIMARY KEY (id)"),
    ("contests_integrityuploadgrant", "contests_integrityuploadgrant_processed_seq_check", "c", "CHECK ((processed_seq >= 0))"),
    ("contests_integrityuploadgrant", "contests_integrityuploadgrant_received_seq_check", "c", "CHECK ((received_seq >= 0))"),
    ("contests_integrityuploadgrant", "uniq_integrity_upload_grant_scope", "u", "UNIQUE (run_id, participant_id, attempt_id, device_id)"),
    ("exam_answers", "exam_answers_graded_by_id_44c198b0_fk_users_id", "f", "FOREIGN KEY (graded_by_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_answers", "exam_answers_participant_id_15feb4d0_fk_contest_participants_id", "f", "FOREIGN KEY (participant_id) REFERENCES contest_participants(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_answers", "exam_answers_participant_id_question_id_774aa33d_uniq", "u", "UNIQUE (participant_id, question_id)"),
    ("exam_answers", "exam_answers_pkey", "p", "PRIMARY KEY (id)"),
    ("exam_answers", "exam_answers_question_id_c84cf77b_fk_exam_questions_id", "f", "FOREIGN KEY (question_id) REFERENCES exam_questions(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_events", "exam_events_contest_id_e2c66062_fk_contests_id", "f", "FOREIGN KEY (contest_id) REFERENCES contests(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_events", "exam_events_event_schema_version_check", "c", "CHECK ((event_schema_version >= 0))"),
    ("exam_events", "exam_events_integrity_command_id_key", "u", "UNIQUE (integrity_command_id)"),
    ("exam_events", "exam_events_integrity_run_id_ed78d0de_fk_exam_integrity_runs_id", "f", "FOREIGN KEY (integrity_run_id) REFERENCES exam_integrity_runs(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_events", "exam_events_pkey", "p", "PRIMARY KEY (id)"),
    ("exam_events", "exam_events_user_id_abd4aba2_fk_users_id", "f", "FOREIGN KEY (user_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_evidence_chunks", "exam_evidence_chunks_byte_size_check", "c", "CHECK ((byte_size >= 0))"),
    ("exam_evidence_chunks", "exam_evidence_chunks_chunk_seq_check", "c", "CHECK ((chunk_seq >= 0))"),
    ("exam_evidence_chunks", "exam_evidence_chunks_contest_id_d78eee7d_fk_contests_id", "f", "FOREIGN KEY (contest_id) REFERENCES contests(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_evidence_chunks", "exam_evidence_chunks_exam_event_id_72426e55_fk_exam_events_id", "f", "FOREIGN KEY (exam_event_id) REFERENCES exam_events(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_evidence_chunks", "exam_evidence_chunks_integrity_run_id_b178cf95_fk_exam_inte", "f", "FOREIGN KEY (integrity_run_id) REFERENCES exam_integrity_runs(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_evidence_chunks", "exam_evidence_chunks_participant_id_2eac34d3_fk_contest_p", "f", "FOREIGN KEY (participant_id) REFERENCES contest_participants(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_evidence_chunks", "exam_evidence_chunks_pkey", "p", "PRIMARY KEY (id)"),
    ("exam_evidence_chunks", "uniq_integrity_evidence_chunk", "u", "UNIQUE (integrity_run_id, participant_id, source, recording_session_id, chunk_seq)"),
    ("exam_evidence_frames", "exam_evidence_frames_byte_size_check", "c", "CHECK ((byte_size >= 0))"),
    ("exam_evidence_frames", "exam_evidence_frames_contest_id_0f559af8_fk_contests_id", "f", "FOREIGN KEY (contest_id) REFERENCES contests(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_evidence_frames", "exam_evidence_frames_exam_event_id_3b04f57b_fk_exam_events_id", "f", "FOREIGN KEY (exam_event_id) REFERENCES exam_events(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_evidence_frames", "exam_evidence_frames_pkey", "p", "PRIMARY KEY (id)"),
    ("exam_evidence_frames", "exam_evidence_frames_seq_check", "c", "CHECK ((seq >= 0))"),
    ("exam_evidence_frames", "exam_evidence_frames_user_id_c8bcfa60_fk_users_id", "f", "FOREIGN KEY (user_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_integrity_runs", "exam_integrity_runs_archive_generation_check", "c", "CHECK ((archive_generation >= 0))"),
    ("exam_integrity_runs", "exam_integrity_runs_contest_id_d038a0d2_fk_contests_id", "f", "FOREIGN KEY (contest_id) REFERENCES contests(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_integrity_runs", "exam_integrity_runs_created_by_id_96e4301a_fk_users_id", "f", "FOREIGN KEY (created_by_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_integrity_runs", "exam_integrity_runs_destroyed_by_id_5c2c90fc_fk_users_id", "f", "FOREIGN KEY (destroyed_by_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_integrity_runs", "exam_integrity_runs_pkey", "p", "PRIMARY KEY (id)"),
    ("exam_integrity_runs", "exam_integrity_runs_purged_by_id_8770049e_fk_users_id", "f", "FOREIGN KEY (purged_by_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_integrity_runs", "exam_integrity_runs_schedule_revision_check", "c", "CHECK ((schedule_revision >= 0))"),
    ("exam_integrity_runs", "exam_integrity_runs_stopped_by_id_66abe5c8_fk_users_id", "f", "FOREIGN KEY (stopped_by_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_question_groups", "exam_question_groups_contest_id_1ee9030d_fk_contests_id", "f", "FOREIGN KEY (contest_id) REFERENCES contests(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_question_groups", "exam_question_groups_pkey", "p", "PRIMARY KEY (id)"),
    ("exam_questions", "exam_questions_contest_id_1a3fe4f3_fk_contests_id", "f", "FOREIGN KEY (contest_id) REFERENCES contests(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_questions", "exam_questions_group_id_c9fff242_fk_exam_question_groups_id", "f", "FOREIGN KEY (group_id) REFERENCES exam_question_groups(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_questions", "exam_questions_order_in_group_check", "c", "CHECK ((order_in_group >= 0))"),
    ("exam_questions", "exam_questions_pkey", "p", "PRIMARY KEY (id)"),
    ("exam_questions", "exam_questions_question_asset_id_007ead29_fk_question_assets_id", "f", "FOREIGN KEY (question_asset_id) REFERENCES question_assets(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_questions", "exam_questions_question_version_id_ec438bb8_fk_question_", "f", "FOREIGN KEY (question_version_id) REFERENCES question_versions(id) DEFERRABLE INITIALLY DEFERRED"),
    ("exam_questions", "exam_questions_score_check", "c", "CHECK ((score >= 0))"),
    ("exam_questions", "uq_exam_question_contest_order", "u", "UNIQUE (contest_id, \"order\") DEFERRABLE INITIALLY DEFERRED"),
)

EXPECTED_INDEXES = (
    ("contest_activities", "contest_act_contest_b7af06_idx", "CREATE INDEX contest_act_contest_b7af06_idx ON contest_activities USING btree (contest_id, created_at)"),
    ("contest_activities", "contest_activities_contest_id_f2180fd0", "CREATE INDEX contest_activities_contest_id_f2180fd0 ON contest_activities USING btree (contest_id)"),
    ("contest_activities", "contest_activities_user_id_bf577cad", "CREATE INDEX contest_activities_user_id_bf577cad ON contest_activities USING btree (user_id)"),
    ("contest_announcements", "contest_announcements_contest_id_575ee8cf", "CREATE INDEX contest_announcements_contest_id_575ee8cf ON contest_announcements USING btree (contest_id)"),
    ("contest_announcements", "contest_announcements_created_by_id_aec9de9b", "CREATE INDEX contest_announcements_created_by_id_aec9de9b ON contest_announcements USING btree (created_by_id)"),
    ("contest_clarifications", "contest_clarifications_author_id_af151407", "CREATE INDEX contest_clarifications_author_id_af151407 ON contest_clarifications USING btree (author_id)"),
    ("contest_clarifications", "contest_clarifications_contest_id_25da9663", "CREATE INDEX contest_clarifications_contest_id_25da9663 ON contest_clarifications USING btree (contest_id)"),
    ("contest_clarifications", "contest_clarifications_problem_id_1f7effed", "CREATE INDEX contest_clarifications_problem_id_1f7effed ON contest_clarifications USING btree (problem_id)"),
    ("contest_participants", "contest_participants_contest_id_09eb8fd9", "CREATE INDEX contest_participants_contest_id_09eb8fd9 ON contest_participants USING btree (contest_id)"),
    ("contest_participants", "contest_participants_user_id_dd24a4e2", "CREATE INDEX contest_participants_user_id_dd24a4e2 ON contest_participants USING btree (user_id)"),
    ("contests", "contests_owner_id_c57994d2", "CREATE INDEX contests_owner_id_c57994d2 ON contests USING btree (owner_id)"),
    ("contests", "contests_status_dc283977", "CREATE INDEX contests_status_dc283977 ON contests USING btree (status)"),
    ("contests", "contests_status_dc283977_like", "CREATE INDEX contests_status_dc283977_like ON contests USING btree (status varchar_pattern_ops)"),
    ("contests_admins", "contests_admins_contest_id_184139c3", "CREATE INDEX contests_admins_contest_id_184139c3 ON contests_admins USING btree (contest_id)"),
    ("contests_admins", "contests_admins_user_id_cdee87cf", "CREATE INDEX contests_admins_user_id_cdee87cf ON contests_admins USING btree (user_id)"),
    ("contests_integritybatchadmission", "contests_integritybatchadmission_participant_id_9f271d22", "CREATE INDEX contests_integritybatchadmission_participant_id_9f271d22 ON contests_integritybatchadmission USING btree (participant_id)"),
    ("contests_integritybatchadmission", "contests_integritybatchadmission_run_id_ac53460e", "CREATE INDEX contests_integritybatchadmission_run_id_ac53460e ON contests_integritybatchadmission USING btree (run_id)"),
    ("contests_integritybatchadmission", "integrity_admission_scope_idx", "CREATE INDEX integrity_admission_scope_idx ON contests_integritybatchadmission USING btree (run_id, participant_id, device_id)"),
    ("contests_integrityuploadgrant", "contests_integrityuploadgrant_participant_id_3d7fef42", "CREATE INDEX contests_integrityuploadgrant_participant_id_3d7fef42 ON contests_integrityuploadgrant USING btree (participant_id)"),
    ("contests_integrityuploadgrant", "contests_integrityuploadgrant_run_id_22c17d52", "CREATE INDEX contests_integrityuploadgrant_run_id_22c17d52 ON contests_integrityuploadgrant USING btree (run_id)"),
    ("exam_answers", "exam_answer_partici_b522f1_idx", "CREATE INDEX exam_answer_partici_b522f1_idx ON exam_answers USING btree (participant_id, question_id)"),
    ("exam_answers", "exam_answers_graded_by_id_44c198b0", "CREATE INDEX exam_answers_graded_by_id_44c198b0 ON exam_answers USING btree (graded_by_id)"),
    ("exam_answers", "exam_answers_participant_id_15feb4d0", "CREATE INDEX exam_answers_participant_id_15feb4d0 ON exam_answers USING btree (participant_id)"),
    ("exam_answers", "exam_answers_question_id_c84cf77b", "CREATE INDEX exam_answers_question_id_c84cf77b ON exam_answers USING btree (question_id)"),
    ("exam_events", "exam_events_contest_e08345_idx", "CREATE INDEX exam_events_contest_e08345_idx ON exam_events USING btree (contest_id, user_id)"),
    ("exam_events", "exam_events_contest_id_e2c66062", "CREATE INDEX exam_events_contest_id_e2c66062 ON exam_events USING btree (contest_id)"),
    ("exam_events", "exam_events_created_f05075_idx", "CREATE INDEX exam_events_created_f05075_idx ON exam_events USING btree (created_at)"),
    ("exam_events", "exam_events_incident_id_b7ab0802", "CREATE INDEX exam_events_incident_id_b7ab0802 ON exam_events USING btree (incident_id)"),
    ("exam_events", "exam_events_integrity_run_id_ed78d0de", "CREATE INDEX exam_events_integrity_run_id_ed78d0de ON exam_events USING btree (integrity_run_id)"),
    ("exam_events", "exam_events_user_id_abd4aba2", "CREATE INDEX exam_events_user_id_abd4aba2 ON exam_events USING btree (user_id)"),
    ("exam_evidence_chunks", "exam_eviden_integri_5da9bf_idx", "CREATE INDEX exam_eviden_integri_5da9bf_idx ON exam_evidence_chunks USING btree (integrity_run_id, incident_id)"),
    ("exam_evidence_chunks", "exam_eviden_partici_22f20d_idx", "CREATE INDEX exam_eviden_partici_22f20d_idx ON exam_evidence_chunks USING btree (participant_id, status)"),
    ("exam_evidence_chunks", "exam_evidence_chunks_contest_id_d78eee7d", "CREATE INDEX exam_evidence_chunks_contest_id_d78eee7d ON exam_evidence_chunks USING btree (contest_id)"),
    ("exam_evidence_chunks", "exam_evidence_chunks_exam_event_id_72426e55", "CREATE INDEX exam_evidence_chunks_exam_event_id_72426e55 ON exam_evidence_chunks USING btree (exam_event_id)"),
    ("exam_evidence_chunks", "exam_evidence_chunks_integrity_run_id_b178cf95", "CREATE INDEX exam_evidence_chunks_integrity_run_id_b178cf95 ON exam_evidence_chunks USING btree (integrity_run_id)"),
    ("exam_evidence_chunks", "exam_evidence_chunks_participant_id_2eac34d3", "CREATE INDEX exam_evidence_chunks_participant_id_2eac34d3 ON exam_evidence_chunks USING btree (participant_id)"),
    ("exam_evidence_frames", "exam_eviden_client__a0c5dd_idx", "CREATE INDEX exam_eviden_client__a0c5dd_idx ON exam_evidence_frames USING btree (client_captured_at_ms)"),
    ("exam_evidence_frames", "exam_eviden_contest_c869b3_idx", "CREATE INDEX exam_eviden_contest_c869b3_idx ON exam_evidence_frames USING btree (contest_id, user_id, exam_event_id)"),
    ("exam_evidence_frames", "exam_eviden_evidenc_b4e034_idx", "CREATE INDEX exam_eviden_evidenc_b4e034_idx ON exam_evidence_frames USING btree (evidence_cluster_id)"),
    ("exam_evidence_frames", "exam_eviden_status_1a5ce0_idx", "CREATE INDEX exam_eviden_status_1a5ce0_idx ON exam_evidence_frames USING btree (status)"),
    ("exam_evidence_frames", "exam_eviden_upload__e16a94_idx", "CREATE INDEX exam_eviden_upload__e16a94_idx ON exam_evidence_frames USING btree (upload_session_id)"),
    ("exam_evidence_frames", "exam_evidence_frames_contest_id_0f559af8", "CREATE INDEX exam_evidence_frames_contest_id_0f559af8 ON exam_evidence_frames USING btree (contest_id)"),
    ("exam_evidence_frames", "exam_evidence_frames_exam_event_id_3b04f57b", "CREATE INDEX exam_evidence_frames_exam_event_id_3b04f57b ON exam_evidence_frames USING btree (exam_event_id)"),
    ("exam_evidence_frames", "exam_evidence_frames_user_id_c8bcfa60", "CREATE INDEX exam_evidence_frames_user_id_c8bcfa60 ON exam_evidence_frames USING btree (user_id)"),
    ("exam_integrity_runs", "exam_integr_contest_e839f6_idx", "CREATE INDEX exam_integr_contest_e839f6_idx ON exam_integrity_runs USING btree (contest_id, session_state)"),
    ("exam_integrity_runs", "exam_integr_data_st_e511a7_idx", "CREATE INDEX exam_integr_data_st_e511a7_idx ON exam_integrity_runs USING btree (data_state, updated_at)"),
    ("exam_integrity_runs", "exam_integrity_runs_contest_id_d038a0d2", "CREATE INDEX exam_integrity_runs_contest_id_d038a0d2 ON exam_integrity_runs USING btree (contest_id)"),
    ("exam_integrity_runs", "exam_integrity_runs_created_by_id_96e4301a", "CREATE INDEX exam_integrity_runs_created_by_id_96e4301a ON exam_integrity_runs USING btree (created_by_id)"),
    ("exam_integrity_runs", "exam_integrity_runs_destroyed_by_id_5c2c90fc", "CREATE INDEX exam_integrity_runs_destroyed_by_id_5c2c90fc ON exam_integrity_runs USING btree (destroyed_by_id)"),
    ("exam_integrity_runs", "exam_integrity_runs_purged_by_id_8770049e", "CREATE INDEX exam_integrity_runs_purged_by_id_8770049e ON exam_integrity_runs USING btree (purged_by_id)"),
    ("exam_integrity_runs", "exam_integrity_runs_stopped_by_id_66abe5c8", "CREATE INDEX exam_integrity_runs_stopped_by_id_66abe5c8 ON exam_integrity_runs USING btree (stopped_by_id)"),
    ("exam_integrity_runs", "uniq_live_integrity_run_per_contest", "CREATE UNIQUE INDEX uniq_live_integrity_run_per_contest ON exam_integrity_runs USING btree (contest_id) WHERE ((session_state)::text = ANY ((ARRAY['prepared'::character varying, 'active'::character varying, 'draining'::character varying])::text[]))"),
    ("exam_question_groups", "exam_questi_contest_b4923c_idx", "CREATE INDEX exam_questi_contest_b4923c_idx ON exam_question_groups USING btree (contest_id, \"order\")"),
    ("exam_question_groups", "exam_question_groups_contest_id_1ee9030d", "CREATE INDEX exam_question_groups_contest_id_1ee9030d ON exam_question_groups USING btree (contest_id)"),
    ("exam_questions", "exam_questi_contest_62adcc_idx", "CREATE INDEX exam_questi_contest_62adcc_idx ON exam_questions USING btree (contest_id, \"order\")"),
    ("exam_questions", "exam_questi_source__6ee487_idx", "CREATE INDEX exam_questi_source__6ee487_idx ON exam_questions USING btree (source_question_id)"),
    ("exam_questions", "exam_questions_contest_id_1a3fe4f3", "CREATE INDEX exam_questions_contest_id_1a3fe4f3 ON exam_questions USING btree (contest_id)"),
    ("exam_questions", "exam_questions_group_id_c9fff242", "CREATE INDEX exam_questions_group_id_c9fff242 ON exam_questions USING btree (group_id)"),
    ("exam_questions", "exam_questions_question_asset_id_007ead29", "CREATE INDEX exam_questions_question_asset_id_007ead29 ON exam_questions USING btree (question_asset_id)"),
    ("exam_questions", "exam_questions_question_version_id_ec438bb8", "CREATE INDEX exam_questions_question_version_id_ec438bb8 ON exam_questions USING btree (question_version_id)"),
)


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0003_baseline"),
    ]

    operations = [
        migrations.RunPython(
            build_alignment(EXPECTED_CONSTRAINTS, EXPECTED_INDEXES),
            migrations.RunPython.noop,
        ),
    ]
