# Generated by Django 4.2.26 on 2025-11-29 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contests", "0003_contest_password_contestparticipant_left_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="標題")),
                ("content", models.TextField(verbose_name="內容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="發布時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="contests.contest",
                        verbose_name="考試",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="發布者",
                    ),
                ),
            ],
            options={
                "verbose_name": "考試公告",
                "verbose_name_plural": "考試公告",
                "db_table": "contest_announcements",
                "ordering": ["-created_at"],
            },
        ),
    ]
