# Generated by Django 4.2.26 on 2025-11-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0004_contestannouncement"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="rules",
            field=models.TextField(blank=True, verbose_name="競賽規定"),
        ),
    ]
