# Generated by Django 4.2.30 on 2026-09-23 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0004_align_legacy_schema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contestparticipant",
            name="rank",
        ),
        migrations.RemoveField(
            model_name="contestparticipant",
            name="score",
        ),
    ]
