# Generated by Django 4.2.26 on 2025-11-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0005_contest_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="allow_multiple_joins",
            field=models.BooleanField(default=False, verbose_name="允許多次加入"),
        ),
        migrations.AddField(
            model_name="contest",
            name="ban_tab_switching",
            field=models.BooleanField(default=False, verbose_name="禁止切換分頁"),
        ),
    ]
