# Generated by Django 4.2.26 on 2025-11-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0006_contest_allow_multiple_joins_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="is_visible",
        ),
        migrations.AlterField(
            model_name="contest",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="是否公開 (無需密碼)"),
        ),
    ]
