# Generated by Django 4.2.26 on 2025-11-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0007_remove_is_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="is_ended",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="主辦者手動標記比賽已結束，只有結束後才能公開題目到練習題庫",
                verbose_name="已結束",
            ),
        ),
    ]
