# Generated by Django 4.2.26 on 2025-11-30 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0003_migrate_practice_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contests", "0008_contest_is_ended"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "考試",
                "verbose_name_plural": "考試",
            },
        ),
        migrations.AddField(
            model_name="contest",
            name="exam_mode_enabled",
            field=models.BooleanField(
                default=False, help_text="啟用全螢幕與防失焦的嚴格考試模式", verbose_name="啟用考試模式"
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="名稱"
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_contests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="主辦者",
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="scoreboard_visible_during_contest",
            field=models.BooleanField(
                default=False,
                help_text="False: 學生只能看自己成績；True: 學生可看完整排行榜",
                verbose_name="比賽中顯示排行榜",
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                db_index=True,
                default="inactive",
                help_text="active: 比賽正在進行，可接受提交；inactive: 比賽已關閉或尚未啟用",
                max_length=20,
                verbose_name="狀態",
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=20,
                verbose_name="可見性",
            ),
        ),
        migrations.AddField(
            model_name="contestparticipant",
            name="has_finished_exam",
            field=models.BooleanField(
                default=False,
                help_text="學生按下「結束考試」後標記，用來控制是否還能繼續送出競賽提交",
                verbose_name="已完成考試",
            ),
        ),
        migrations.AddField(
            model_name="contestproblem",
            name="label",
            field=models.CharField(
                default="A", help_text="例如: A, B, C", max_length=10, verbose_name="標籤"
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_contests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="建立者 (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="結束時間"),
        ),
        migrations.AlterField(
            model_name="contest",
            name="is_ended",
            field=models.BooleanField(
                default=False,
                help_text="Use status field instead",
                verbose_name="已結束 (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="是否公開 (deprecated)"),
        ),
        migrations.AlterField(
            model_name="contest",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="開始時間"),
        ),
        migrations.AlterField(
            model_name="contest",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="標題 (deprecated)"
            ),
        ),
        migrations.AlterField(
            model_name="contestparticipant",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="contests.contest",
            ),
        ),
        migrations.AlterField(
            model_name="contestproblem",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contest_problems",
                to="contests.contest",
            ),
        ),
        migrations.CreateModel(
            name="Clarification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="問題")),
                ("answer", models.TextField(blank=True, null=True, verbose_name="回答")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="是否對所有參賽者公開此 Q&A", verbose_name="公開"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("answered", "Answered")],
                        default="pending",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提問時間"),
                ),
                (
                    "answered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="回答時間"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_clarifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提問者",
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clarifications",
                        to="contests.contest",
                        verbose_name="考試",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        help_text="若為 null 則為一般問題",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clarifications",
                        to="problems.problem",
                        verbose_name="題目",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clarification",
                "verbose_name_plural": "Clarifications",
                "db_table": "contest_clarifications",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("tab_hidden", "Tab Hidden"),
                            ("window_blur", "Window Blur"),
                            ("exit_fullscreen", "Exit Fullscreen"),
                            ("forbidden_focus_event", "Forbidden Focus Event"),
                        ],
                        max_length=50,
                        verbose_name="事件類型",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="JSON 格式的額外事件資訊",
                        null=True,
                        verbose_name="額外資訊",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="發生時間"),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_events",
                        to="contests.contest",
                        verbose_name="考試",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="學生",
                    ),
                ),
            ],
            options={
                "verbose_name": "考試事件",
                "verbose_name_plural": "考試事件",
                "db_table": "exam_events",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["contest", "user"],
                        name="exam_events_contest_e08345_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="exam_events_created_f05075_idx"
                    ),
                ],
            },
        ),
    ]
