# Generated by Django 4.2.26 on 2025-11-30 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0009_alter_contest_options_contest_exam_mode_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="contest",
            name="is_ended",
        ),
        migrations.RemoveField(
            model_name="contest",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="contest",
            name="title",
        ),
        migrations.DeleteModel(
            name="ContestQuestion",
        ),
    ]
