# Generated by Django 4.2.26 on 2025-11-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0010_remove_contest_creator_remove_contest_is_ended_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipant",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="開始時間"),
        ),
    ]
