# Generated by Django 4.2.26 on 2025-12-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0011_contestparticipant_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipant",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="是否因違規而被鎖定", verbose_name="已鎖定"
            ),
        ),
        migrations.AddField(
            model_name="contestparticipant",
            name="lock_reason",
            field=models.TextField(blank=True, verbose_name="鎖定原因"),
        ),
    ]
