# Generated by Django 4.2.26 on 2025-12-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0012_contestparticipant_is_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="max_cheat_warnings",
            field=models.IntegerField(
                default=0,
                help_text="Number of warnings before locking (0 = immediate lock)",
            ),
        ),
    ]
