# Generated by Django 4.2.26 on 2025-12-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0013_contest_max_cheat_warnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipant",
            name="violation_count",
            field=models.IntegerField(default=0, verbose_name="違規次數"),
        ),
    ]
