# Generated by Django 4.2.26 on 2025-12-01 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contests", "0014_contestparticipant_violation_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("register", "Register"),
                            ("enter_contest", "Enter Contest"),
                            ("start_exam", "Start Exam"),
                            ("end_exam", "End Exam"),
                            ("lock_user", "Lock User"),
                            ("unlock_user", "Unlock User"),
                            ("submit_code", "Submit Code"),
                            ("ask_question", "Ask Question"),
                            ("reply_question", "Reply Question"),
                            ("update_problem", "Update Problem"),
                            ("announce", "Announce"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="動作類型",
                    ),
                ),
                ("details", models.TextField(verbose_name="詳細內容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="發生時間"),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="contests.contest",
                        verbose_name="考試",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "競賽活動",
                "verbose_name_plural": "競賽活動",
                "db_table": "contest_activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["contest", "created_at"],
                        name="contest_act_contest_b7af06_idx",
                    )
                ],
            },
        ),
    ]
