# Generated by Django 4.2.26 on 2025-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0015_contestactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="inactive",
                help_text="active: 比賽正在進行，可接受提交；inactive: 比賽已關閉或尚未啟用",
                max_length=20,
                verbose_name="狀態",
            ),
        ),
    ]
