# Generated by Django 4.2.26 on 2025-12-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0016_alter_contest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="allow_auto_unlock",
            field=models.BooleanField(default=False, verbose_name="允許自動解鎖"),
        ),
        migrations.AddField(
            model_name="contest",
            name="auto_unlock_minutes",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="自動解鎖時間 (分鐘)"
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="ban_tab_switching",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contest",
            name="max_cheat_warnings",
            field=models.IntegerField(default=3),
        ),
    ]
