# Generated by Django 4.2.26 on 2025-12-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0017_contest_allow_auto_unlock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipant",
            name="is_paused",
            field=models.BooleanField(
                default=False, help_text="是否處於暫停狀態（需手動點擊繼續）", verbose_name="已暫停"
            ),
        ),
    ]
