# Generated by Django 4.2.26 on 2025-12-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0018_contestparticipant_is_paused"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipant",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="鎖定時間"),
        ),
    ]
