# Generated by Django 4.2.27 on 2025-12-07 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0019_contestparticipant_locked_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contestproblem",
            name="label",
        ),
    ]
