# Generated by Django 4.2.27 on 2025-12-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0020_remove_contestproblem_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipant",
            name="exam_status",
            field=models.CharField(
                choices=[
                    ("not_started", "未開始"),
                    ("in_progress", "進行中"),
                    ("paused", "暫停"),
                    ("locked", "已鎖定"),
                    ("submitted", "已交卷"),
                ],
                default="not_started",
                help_text="學生考試狀態：未開始/進行中/暫停/已鎖定/已交卷",
                max_length=20,
                verbose_name="考試狀態",
            ),
        ),
    ]
