# Generated by Django 4.2.27 on 2025-12-07 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0021_add_exam_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="ban_tab_switching",
        ),
        migrations.RemoveField(
            model_name="contestparticipant",
            name="has_finished_exam",
        ),
        migrations.RemoveField(
            model_name="contestparticipant",
            name="is_locked",
        ),
        migrations.RemoveField(
            model_name="contestparticipant",
            name="is_paused",
        ),
        migrations.RemoveField(
            model_name="contestproblem",
            name="score",
        ),
    ]
