# Generated by Django 4.2.27 on 2025-12-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0022_remove_contest_ban_tab_switching_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="anonymous_mode_enabled",
            field=models.BooleanField(
                default=False,
                help_text="啟用後學生可使用暱稱參與競賽，排行榜和提交列表顯示暱稱",
                verbose_name="啟用匿名模式",
            ),
        ),
        migrations.AddField(
            model_name="contestparticipant",
            name="nickname",
            field=models.CharField(
                blank=True,
                default="",
                help_text="匿名模式下顯示的名稱，預設為用戶名",
                max_length=50,
                verbose_name="暱稱",
            ),
        ),
    ]
