# Generated by Django 4.2.27 on 2025-12-08 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contests", "0023_anonymous_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                help_text="除 owner 外的其他管理者 (teachers)",
                related_name="admin_contests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="管理員",
            ),
        ),
    ]
