# Generated by Django 4.2.27 on 2025-12-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0025_contestparticipant_last_heartbeat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestactivity",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("enter_contest", "Enter Contest"),
                    ("start_exam", "Start Exam"),
                    ("end_exam", "End Exam"),
                    ("auto_submit", "Auto Submit"),
                    ("lock_user", "Lock User"),
                    ("unlock_user", "Unlock User"),
                    ("submit_code", "Submit Code"),
                    ("ask_question", "Ask Question"),
                    ("reply_question", "Reply Question"),
                    ("update_contest", "Update Contest"),
                    ("update_problem", "Update Problem"),
                    ("update_participant", "Update Participant"),
                    ("announce", "Announce"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="動作類型",
            ),
        ),
    ]
