# Generated by Django 4.2.28 on 2026-02-25 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0029_hash_private_contest_passwords"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="examquestion",
            new_name="exam_questi_contest_62adcc_idx",
            old_name="exam_questio_contest_5204a7_idx",
        ),
    ]
