# Generated by Django 4.2.28 on 2026-02-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "contests",
            "0030_rename_exam_questio_contest_5204a7_idx_exam_questi_contest_62adcc_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("true_false", "是非題"),
                    ("single_choice", "單選題"),
                    ("multiple_choice", "多選題"),
                    ("short_answer", "簡答題"),
                    ("essay", "問答題"),
                ],
                default="single_choice",
                max_length=30,
                verbose_name="題型",
            ),
        ),
    ]
