# Generated by Django 4.2.28 on 2026-02-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0032_add_exam_answer_and_results_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="examanswer",
            name="question_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="首次作答時記錄的題目狀態，用於確保批改時參照學生作答時的題目",
                null=True,
                verbose_name="題目快照",
            ),
        ),
    ]
