# Generated by Django 4.2.28 on 2026-03-02 18:19

from django.db import migrations, models


def populate_contest_type(apps, schema_editor):
    """Set contest_type based on existing exam_mode_enabled value."""
    Contest = apps.get_model("contests", "Contest")
    Contest.objects.filter(cheat_detection_enabled=True).update(contest_type="paper_exam")


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0034_add_warning_timeout_force_submit_locked_event_types"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contest",
            old_name="exam_mode_enabled",
            new_name="cheat_detection_enabled",
        ),
        migrations.AlterField(
            model_name="contest",
            name="cheat_detection_enabled",
            field=models.BooleanField(
                default=False,
                help_text="啟用全螢幕與防失焦的嚴格防作弊模式",
                verbose_name="啟用防作弊模式",
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="contest_type",
            field=models.CharField(
                choices=[("coding", "Coding Test"), ("paper_exam", "Paper Exam")],
                default="coding",
                help_text="coding: 程式題; paper_exam: 紙筆題考試",
                max_length=15,
                verbose_name="比賽類型",
            ),
        ),
        migrations.RunPython(populate_contest_type, migrations.RunPython.noop),
    ]
