# Generated by Django 4.2 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0036_alter_examevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipant",
            name="submit_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="手動或系統自動交卷原因",
                verbose_name="交卷原因",
            ),
        ),
    ]

