# Generated by Django 4.2.28 on 2026-03-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0037_contestparticipant_submit_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("tab_hidden", "Tab Hidden"),
                    ("window_blur", "Window Blur"),
                    ("exit_fullscreen", "Exit Fullscreen"),
                    ("forbidden_focus_event", "Forbidden Focus Event"),
                    ("forbidden_action", "Forbidden Action"),
                    ("multiple_displays", "Multiple Displays"),
                    ("mouse_leave", "Mouse Leave"),
                    ("warning_timeout", "Warning Timeout"),
                    ("force_submit_locked", "Force Submit Locked"),
                ],
                max_length=50,
                verbose_name="事件類型",
            ),
        ),
    ]
