# Generated by Django 4.2.28 on 2026-03-05 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contests", "0038_alter_examevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestactivity",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("enter_contest", "Enter Contest"),
                    ("start_exam", "Start Exam"),
                    ("end_exam", "End Exam"),
                    ("auto_submit", "Auto Submit"),
                    ("lock_user", "Lock User"),
                    ("unlock_user", "Unlock User"),
                    ("submit_code", "Submit Code"),
                    ("ask_question", "Ask Question"),
                    ("reply_question", "Reply Question"),
                    ("update_contest", "Update Contest"),
                    ("update_problem", "Update Problem"),
                    ("update_participant", "Update Participant"),
                    ("concurrent_login_detected", "Concurrent Login Detected"),
                    ("takeover_lock", "Takeover Lock"),
                    ("takeover_approve", "Takeover Approve"),
                    ("announce", "Announce"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="動作類型",
            ),
        ),
        migrations.AlterField(
            model_name="contestparticipant",
            name="exam_status",
            field=models.CharField(
                choices=[
                    ("not_started", "未開始"),
                    ("in_progress", "進行中"),
                    ("paused", "暫停"),
                    ("locked", "已鎖定"),
                    ("locked_takeover", "接管鎖定"),
                    ("submitted", "已交卷"),
                ],
                default="not_started",
                help_text="學生考試狀態：未開始/進行中/暫停/已鎖定/接管鎖定/已交卷",
                max_length=20,
                verbose_name="考試狀態",
            ),
        ),
        migrations.AlterField(
            model_name="examevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("tab_hidden", "Tab Hidden"),
                    ("window_blur", "Window Blur"),
                    ("exit_fullscreen", "Exit Fullscreen"),
                    ("forbidden_focus_event", "Forbidden Focus Event"),
                    ("forbidden_action", "Forbidden Action"),
                    ("multiple_displays", "Multiple Displays"),
                    ("mouse_leave", "Mouse Leave"),
                    ("warning_timeout", "Warning Timeout"),
                    ("force_submit_locked", "Force Submit Locked"),
                    ("screen_share_stopped", "Screen Share Stopped"),
                    ("screen_share_invalid_surface", "Screen Share Invalid Surface"),
                    ("capture_upload_degraded", "Capture Upload Degraded"),
                    ("concurrent_login_detected", "Concurrent Login Detected"),
                    ("takeover_locked", "Takeover Locked"),
                    ("takeover_approved", "Takeover Approved"),
                ],
                max_length=50,
                verbose_name="事件類型",
            ),
        ),
        migrations.CreateModel(
            name="ExamEvidenceJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_session_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("raw_count", models.PositiveIntegerField(default=0)),
                ("video_bucket", models.CharField(blank=True, default="", max_length=128)),
                ("video_key", models.CharField(blank=True, default="", max_length=512)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contest",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence_jobs", to="contests.contest"),
                ),
                (
                    "participant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence_jobs", to="contests.contestparticipant"),
                ),
            ],
            options={
                "db_table": "exam_evidence_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["contest", "status"], name="exam_eviden_contest_2bf0d4_idx"),
                    models.Index(fields=["participant", "created_at"], name="exam_eviden_partici_a82453_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contest", "participant", "upload_session_id"),
                        name="uniq_evidence_job_contest_participant_session",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExamEvidenceVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upload_session_id", models.CharField(blank=True, default="", max_length=64)),
                ("bucket", models.CharField(max_length=128)),
                ("object_key", models.CharField(max_length=512)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("frame_count", models.PositiveIntegerField(default=0)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("is_suspected", models.BooleanField(default=False)),
                ("suspected_note", models.TextField(blank=True, default="")),
                ("suspected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contest",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence_videos", to="contests.contest"),
                ),
                (
                    "participant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence_videos", to="contests.contestparticipant"),
                ),
                (
                    "suspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flagged_exam_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exam_evidence_videos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["contest", "participant"], name="exam_eviden_contest_5f7ba0_idx"),
                    models.Index(fields=["contest", "is_suspected"], name="exam_eviden_contest_0efcb1_idx"),
                ],
            },
        ),
    ]
