# Generated by Django 4.2.29 on 2026-03-05 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0039_add_evidence_models_and_takeover_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contestparticipant",
            name="last_heartbeat",
        ),
    ]
