# Generated by Django 4.2.29 on 2026-03-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0040_remove_contestparticipant_last_heartbeat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("tab_hidden", "Tab Hidden"),
                    ("window_blur", "Window Blur"),
                    ("exit_fullscreen", "Exit Fullscreen"),
                    ("forbidden_focus_event", "Forbidden Focus Event"),
                    ("forbidden_action", "Forbidden Action"),
                    ("multiple_displays", "Multiple Displays"),
                    ("mouse_leave", "Mouse Leave"),
                    ("warning_timeout", "Warning Timeout"),
                    ("force_submit_locked", "Force Submit Locked"),
                    ("screen_share_stopped", "Screen Share Stopped"),
                    ("screen_share_invalid_surface", "Screen Share Invalid Surface"),
                    ("capture_upload_degraded", "Capture Upload Degraded"),
                    ("exam_entered", "Exam Entered"),
                    ("exam_submit_initiated", "Exam Submit Initiated"),
                    ("concurrent_login_detected", "Concurrent Login Detected"),
                    ("takeover_locked", "Takeover Locked"),
                    ("takeover_approved", "Takeover Approved"),
                ],
                max_length=50,
                verbose_name="事件類型",
            ),
        ),
    ]
