# Generated by Django 4.2.29 on 2026-03-09 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0042_add_heartbeat_and_tamper_event_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="allow_view_results",
        ),
    ]
