# Generated by Django 4.2.29 on 2026-03-19 10:44

import apps.contests.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0047_alter_examevent_event_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="webcam_module_enabled",
        ),
        migrations.RemoveField(
            model_name="contest",
            name="webcam_required_on_tablet",
        ),
        migrations.AddField(
            model_name="contest",
            name="anticheat_device_policy",
            field=models.JSONField(
                default=apps.contests.models.default_anticheat_device_policy,
                help_text="依裝置定義 sources/detectors 的監考策略",
                verbose_name="防作弊裝置策略",
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="warning_timeout_seconds",
            field=models.PositiveIntegerField(
                default=20, help_text="警告框顯示後，需等待幾秒才可手動關閉", verbose_name="警告框冷卻秒數"
            ),
        ),
    ]
