# Generated by Django 5.2.5 on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0056_examquestion_source_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='question_edit_lock_trigger',
            field=models.CharField(
                blank=True,
                choices=[('coding_submission', 'Coding Submission'), ('exam_answer', 'Exam Answer')],
                max_length=32,
                null=True,
                verbose_name='題目鎖定觸發來源',
            ),
        ),
        migrations.AddField(
            model_name='contest',
            name='question_edit_locked',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='任一學生正式作答後鎖定整場競賽題目編輯',
                verbose_name='題目編輯已鎖定',
            ),
        ),
        migrations.AddField(
            model_name='contest',
            name='question_edit_locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='題目鎖定時間'),
        ),
    ]
