# Generated by Codex on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0058_uuid_cutover_problem_question_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="delivery_mode",
            field=models.CharField(
                choices=[("exam", "Exam"), ("practice", "Practice")],
                db_index=True,
                default="exam",
                help_text="exam: 正式考試流程; practice: 教室練習/作業流程",
                max_length=12,
                verbose_name="交付模式",
            ),
        ),
        migrations.AddField(
            model_name="contestparticipant",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="接受時間"),
        ),
        migrations.AddField(
            model_name="contestparticipant",
            name="assignment_state",
            field=models.CharField(
                choices=[
                    ("unaccepted", "未接受"),
                    ("accepted", "已接受"),
                    ("submitted", "已提交"),
                ],
                db_index=True,
                default="accepted",
                help_text="practice 模式使用：未接受/已接受/已提交",
                max_length=20,
                verbose_name="作業狀態",
            ),
        ),
        migrations.AddField(
            model_name="contestparticipant",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="作業提交時間"),
        ),
    ]
