# Fix: exam_questions.legacy_int_id was still an identity column after migration 0058,
# preventing inserts where legacy_int_id is NULL (e.g., import-from-bank).
# Root cause: DROP IDENTITY IF EXISTS in 0058 silently no-op'd because the column
# was GENERATED BY DEFAULT, requiring an explicit DROP IDENTITY (without IF EXISTS)
# after the identity is already present.

from django.db import migrations


def fix_legacy_int_id(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT attidentity
            FROM pg_attribute
            JOIN pg_class ON pg_class.oid = pg_attribute.attrelid
            WHERE pg_class.relname = 'exam_questions'
              AND attname = 'legacy_int_id'
            """
        )
        row = cursor.fetchone()
        if row and row[0] in ('a', 'd'):
            # Column is still an identity column; make it overridable then drop identity.
            cursor.execute(
                'ALTER TABLE "exam_questions" ALTER COLUMN "legacy_int_id" SET GENERATED BY DEFAULT'
            )
            cursor.execute(
                'ALTER TABLE "exam_questions" ALTER COLUMN "legacy_int_id" DROP IDENTITY'
            )

        # Ensure NOT NULL is removed regardless.
        cursor.execute(
            """
            SELECT is_nullable
            FROM information_schema.columns
            WHERE table_name = 'exam_questions' AND column_name = 'legacy_int_id'
            """
        )
        row = cursor.fetchone()
        if row and row[0] == 'NO':
            cursor.execute(
                'ALTER TABLE "exam_questions" ALTER COLUMN "legacy_int_id" DROP NOT NULL'
            )


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0059_contest_practice_delivery_mode"),
    ]

    operations = [
        migrations.RunPython(fix_legacy_int_id, migrations.RunPython.noop),
    ]
