# Generated by Django 4.2.29 on 2026-03-29 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0060_fix_exam_questions_legacy_int_id_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examquestion",
            name="legacy_int_id",
        ),
    ]
