# Generated by Django 4.2.29 on 2026-03-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0062_contest_screen_share_recovery_grace_ms"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contestproblem",
            index=models.Index(
                fields=["source_question_id"], name="contest_pro_source__019523_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examquestion",
            index=models.Index(
                fields=["source_question_id"], name="exam_questi_source__6ee487_idx"
            ),
        ),
    ]
