# Generated by Django 4.2.29 on 2026-04-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0065_exam_question_import_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="counts_toward_grade",
            field=models.BooleanField(
                default=True,
                help_text="True: 作業/考試（成績計入成績簿）; False: 純練習（僅保留最新提交、不計分）",
                verbose_name="計入正式成績",
            ),
        ),
    ]
