# Generated by Django 4.2.30 on 2026-04-11 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank", "0016_remove_contest_problem_model"),
        ("contests", "0068_delete_examquestionimportsession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="problems",
        ),
        migrations.DeleteModel(
            name="ContestProblem",
        ),
    ]
