# Generated by Codex on 2026-04-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contests", "0073_add_clipboard_action_exam_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamEvidenceFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_cluster_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "source_module",
                    models.CharField(
                        choices=[
                            ("screen_share", "Screen Share"),
                            ("webcam", "Webcam"),
                        ],
                        default="screen_share",
                        max_length=20,
                    ),
                ),
                (
                    "capture_origin",
                    models.CharField(
                        choices=[("student_local", "Student Local")],
                        default="student_local",
                        max_length=32,
                    ),
                ),
                (
                    "evidence_mode",
                    models.CharField(
                        choices=[
                            ("anchor_window", "Anchor Window"),
                            ("pre_loss", "Pre Loss"),
                            ("audit", "Audit"),
                        ],
                        default="anchor_window",
                        max_length=20,
                    ),
                ),
                (
                    "upload_session_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("seq", models.PositiveIntegerField(default=0)),
                ("object_key", models.TextField(blank=True, default="")),
                ("client_captured_at_ms", models.BigIntegerField(blank=True, null=True)),
                ("server_issued_at", models.DateTimeField(auto_now_add=True)),
                ("storage_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("uploaded", "Uploaded"),
                            ("failed", "Failed"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("content_type", models.CharField(default="image/webp", max_length=64)),
                ("byte_size", models.PositiveIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_evidence_frames",
                        to="contests.contest",
                        verbose_name="考試",
                    ),
                ),
                (
                    "exam_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_frames",
                        to="contests.examevent",
                        verbose_name="考試事件",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_evidence_frames",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="學生",
                    ),
                ),
            ],
            options={
                "verbose_name": "考試證據影格",
                "verbose_name_plural": "考試證據影格",
                "db_table": "exam_evidence_frames",
                "ordering": ["client_captured_at_ms", "seq", "id"],
                "indexes": [
                    models.Index(
                        fields=["contest", "user", "exam_event"],
                        name="exam_eviden_contest_c869b3_idx",
                    ),
                    models.Index(
                        fields=["evidence_cluster_id"],
                        name="exam_eviden_evidenc_b4e034_idx",
                    ),
                    models.Index(
                        fields=["upload_session_id"],
                        name="exam_eviden_upload__e16a94_idx",
                    ),
                    models.Index(fields=["status"], name="exam_eviden_status_1a5ce0_idx"),
                    models.Index(
                        fields=["client_captured_at_ms"],
                        name="exam_eviden_client__a0c5dd_idx",
                    ),
                ],
            },
        ),
    ]
