# Generated by Django 4.2.30 on 2026-05-11 19:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0081_remove_auto_unlock_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="examquestion",
            name="answer_format",
            field=models.CharField(
                choices=[
                    ("plain_text", "純文字"),
                    ("markdown", "Markdown"),
                    ("markdown_math", "Markdown + 數學式"),
                ],
                default="plain_text",
                max_length=32,
                verbose_name="答案格式",
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="order_in_group",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="題組內排序"
            ),
        ),
        migrations.CreateModel(
            name="ExamQuestionGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="題組標題"
                    ),
                ),
                (
                    "shared_stem_markdown",
                    models.TextField(blank=True, default="", verbose_name="共同題幹"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_question_groups",
                        to="contests.contest",
                        verbose_name="考試",
                    ),
                ),
            ],
            options={
                "verbose_name": "考卷題組",
                "verbose_name_plural": "考卷題組",
                "db_table": "exam_question_groups",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="examquestion",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="contests.examquestiongroup",
                verbose_name="題組",
            ),
        ),
        migrations.AddIndex(
            model_name="examquestiongroup",
            index=models.Index(
                fields=["contest", "order"], name="exam_questi_contest_b4923c_idx"
            ),
        ),
    ]
