# Generated by Django 4.2.30 on 2026-06-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0084_examquestion_score_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="examquestion",
            name="score_policy_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='redistribute 模式使用：{"redistribute_to": ["question_uuid1", ...]}，空陣列表示全選',
                verbose_name="計分策略設定",
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="score_policy",
            field=models.CharField(
                choices=[
                    ("normal", "正常計分"),
                    ("excluded", "不計分"),
                    ("full_marks", "送分"),
                    ("redistribute", "配分重分配"),
                ],
                default="normal",
                help_text="normal=正常計分, excluded=不計分, full_marks=送分, redistribute=配分重分配",
                max_length=16,
                verbose_name="計分策略",
            ),
        ),
    ]
