# Generated by Django 4.2.30 on 2026-07-26 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0091_add_other_devices_logged_out_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="screen_share_recovery_grace_ms",
        ),
        migrations.RemoveField(
            model_name="contest",
            name="warning_timeout_seconds",
        ),
    ]
