# Generated by Django 4.2.30 on 2026-08-10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0092_remove_legacy_anticheat_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examanswer",
            name="question_snapshot",
        ),
    ]
