# Generated by Django 4.2.30 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0093_remove_examanswer_question_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="question_edit_lock_trigger",
            field=models.CharField(
                blank=True,
                choices=[
                    ("coding_submission", "Coding Submission"),
                    ("exam_answer", "Exam Answer"),
                    ("exam_started", "Exam Started"),
                ],
                max_length=32,
                null=True,
                verbose_name="題目鎖定觸發來源",
            ),
        ),
    ]
