# Generated by Django 4.2.30 on 2026-09-07 09:15

from django.db import migrations, models


def map_legacy_sessions(apps, schema_editor):
    runs = apps.get_model("contests", "ExamIntegrityRun").objects.using(schema_editor.connection.alias)
    runs.filter(compute_state="running").update(session_state="active")
    runs.filter(compute_state="stopping").update(session_state="draining")
    runs.filter(data_state__in=("archived", "purged")).update(session_state="archived")
    runs.filter(compute_state="destroyed").update(session_state="closed")
    if schema_editor.connection.vendor == "postgresql":
        # Flush deferred FK checks before rebuilding the partial unique index.
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


def require_legacy_only(apps, schema_editor):
    # Removing ownership information would reroute resident data to a legacy
    # Worker; multiple archived resident runs also violate the old unique index.
    # Product rollback is the new-run setting, not destructive schema reversal.
    runs = apps.get_model("contests", "ExamIntegrityRun").objects.using(schema_editor.connection.alias)
    if runs.filter(execution_backend="resident").exists():
        raise RuntimeError("Cannot reverse resident sessions while resident-owned runs exist; use INTEGRITY_EXECUTION_BACKEND=legacy for rollback.")


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0096_remove_contest_visibility"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="examintegrityrun",
            name="uniq_live_integrity_run_per_contest",
        ),
        migrations.AddField(
            model_name="contest",
            name="schedule_revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="examintegrityrun",
            name="accept_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examintegrityrun",
            name="execution_backend",
            field=models.CharField(
                choices=[("legacy", "Legacy"), ("resident", "Resident")],
                default="legacy",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="examintegrityrun",
            name="schedule_revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="examintegrityrun",
            name="session_state",
            field=models.CharField(
                choices=[
                    ("prepared", "Prepared"),
                    ("active", "Active"),
                    ("draining", "Draining"),
                    ("archived", "Archived"),
                    ("closed", "Closed"),
                ],
                default="prepared",
                max_length=16,
            ),
        ),
        migrations.RunPython(map_legacy_sessions, require_legacy_only),
        migrations.AddConstraint(
            model_name="examintegrityrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("session_state__in", ("prepared", "active", "draining")),
                    models.Q(
                        ("execution_backend", "legacy"), ("session_state", "archived")
                    ),
                    _connector="OR",
                ),
                fields=("contest",),
                name="uniq_live_integrity_run_per_contest",
            ),
        ),
    ]
