# Generated by Django 4.2.30 on 2026-09-07 10:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


def assign_existing_attempts(apps, schema_editor):
    participant = apps.get_model("contests", "ContestParticipant")
    batch = []
    for row in (
        participant.objects.using(schema_editor.connection.alias)
        .only("id")
        .iterator(chunk_size=1000)
    ):
        row.integrity_attempt_id = uuid.uuid4()
        batch.append(row)
        if len(batch) == 1000:
            participant.objects.using(schema_editor.connection.alias).bulk_update(
                batch, ["integrity_attempt_id"]
            )
            batch = []
    if batch:
        participant.objects.using(schema_editor.connection.alias).bulk_update(
            batch, ["integrity_attempt_id"]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0097_resident_integrity_sessions"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrityBatchAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.UUIDField()),
                ("attempt_id", models.UUIDField()),
                ("device_id", models.CharField(max_length=128)),
                ("body_sha256", models.CharField(max_length=64)),
                ("first_seq", models.PositiveBigIntegerField()),
                ("last_seq", models.PositiveBigIntegerField()),
                ("first_received_at", models.DateTimeField()),
                ("late_unverified", models.BooleanField(default=False)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contests.contestparticipant",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contests.examintegrityrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "batch_id"),
                        name="uniq_integrity_batch_admission",
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["run", "participant", "device_id"],
                        name="integrity_admission_scope_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="contestparticipant",
            name="integrity_attempt_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(assign_existing_attempts, migrations.RunPython.noop),
        migrations.CreateModel(
            name="IntegrityUploadGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=128)),
                ("attempt_id", models.UUIDField()),
                ("submitted_at", models.DateTimeField()),
                ("accept_until", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("final_seq", models.PositiveBigIntegerField(blank=True, null=True)),
                ("received_seq", models.PositiveBigIntegerField(default=0)),
                ("processed_seq", models.PositiveBigIntegerField(default=0)),
                ("commands_drained", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contests.contestparticipant",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contests.examintegrityrun",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="integrityuploadgrant",
            constraint=models.UniqueConstraint(
                fields=("run", "participant", "attempt_id", "device_id"),
                name="uniq_integrity_upload_grant_scope",
            ),
        ),
    ]
