# Generated by Django 4.2.30 on 2026-09-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0098_integrity_upload_grants"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="examintegrityrun",
            name="uniq_live_integrity_run_per_contest",
        ),
        migrations.RemoveIndex(
            model_name="examintegrityrun",
            name="exam_integr_contest_b89025_idx",
        ),
        migrations.RemoveField(
            model_name="examintegrityrun",
            name="compute_state",
        ),
        migrations.RemoveField(
            model_name="examintegrityrun",
            name="container_id",
        ),
        migrations.RemoveField(
            model_name="examintegrityrun",
            name="container_name",
        ),
        migrations.RemoveField(
            model_name="examintegrityrun",
            name="execution_backend",
        ),
        migrations.RemoveField(
            model_name="examintegrityrun",
            name="token_digest",
        ),
        migrations.RemoveField(
            model_name="examintegrityrun",
            name="token_expires_at",
        ),
        migrations.RemoveField(
            model_name="examintegrityrun",
            name="token_revoked_at",
        ),
        migrations.RemoveField(
            model_name="examintegrityrun",
            name="worker_image",
        ),
        migrations.RemoveField(
            model_name="examintegrityrun",
            name="worker_image_digest",
        ),
        migrations.RemoveField(
            model_name="examintegrityrun",
            name="worker_url",
        ),
        migrations.AddIndex(
            model_name="examintegrityrun",
            index=models.Index(
                fields=["contest", "session_state"],
                name="exam_integr_contest_e839f6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="examintegrityrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("session_state__in", ("prepared", "active", "draining"))
                ),
                fields=("contest",),
                name="uniq_live_integrity_run_per_contest",
            ),
        ),
    ]
