# Generated by Django 4.2.27 on 2026-01-23 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("problems", "0010_add_discussion_and_comment_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AISession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("gate0", "需求解析"),
                            ("gate1", "題目生成"),
                            ("preview", "預覽確認"),
                            ("confirmed", "已確認"),
                            ("cancelled", "已取消"),
                        ],
                        default="gate0",
                        max_length=20,
                        verbose_name="階段",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="存儲需求解析結果、用戶選擇等",
                        verbose_name="上下文資料",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="每個用戶同時只有一個活躍的 session",
                        verbose_name="是否活躍",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "created_problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_sessions",
                        to="problems.problem",
                        verbose_name="創建的題目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 聊天 Session",
                "verbose_name_plural": "AI 聊天 Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "用戶"),
                            ("assistant", "AI 助手"),
                            ("system", "系統"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="訊息內容")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "文字"),
                            ("options", "選項"),
                            ("preview", "預覽"),
                            ("error", "錯誤"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="訊息類型",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="存儲選項、預覽資料等額外資訊",
                        verbose_name="元資料",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai.aisession",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 聊天訊息",
                "verbose_name_plural": "AI 聊天訊息",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aisession",
            index=models.Index(
                fields=["user", "is_active"], name="ai_aisessio_user_id_3156dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aisession",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_aisessio_user_id_15a4ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimessage",
            index=models.Index(
                fields=["session", "created_at"], name="ai_aimessag_session_eff8c3_idx"
            ),
        ),
    ]
