# Generated by Django 4.2.27 on 2026-01-25 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("user_message", models.TextField(verbose_name="用戶訊息")),
                (
                    "raw_log",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="完整的 API 請求/回應、工具調用、思考過程等",
                        verbose_name="原始日誌",
                    ),
                ),
                (
                    "ai_response",
                    models.TextField(blank=True, null=True, verbose_name="AI 回應"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="任意的額外資訊：model, tokens, skill, tools used 等",
                        verbose_name="元資訊",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_logs",
                        to="ai.aisession",
                        verbose_name="Session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 執行紀錄",
                "verbose_name_plural": "AI 執行紀錄",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ai_aiexecut_user_id_ac686f_idx",
                    ),
                    models.Index(
                        fields=["session", "-created_at"],
                        name="ai_aiexecut_session_16405e_idx",
                    ),
                ],
            },
        ),
    ]
