# Generated by Django 4.2.28 on 2026-02-25 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0006_add_pending_action"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="aisession",
            name="ai_aisessio_user_id_3156dc_idx",
        ),
        migrations.RenameIndex(
            model_name="aipendingaction",
            new_name="ai_aipendin_session_1a6cec_idx",
            old_name="ai_pendingact_sess_status_idx",
        ),
        migrations.RenameIndex(
            model_name="aipendingaction",
            new_name="ai_aipendin_user_id_4d61dd_idx",
            old_name="ai_pendingact_user_created_idx",
        ),
        migrations.AlterField(
            model_name="aisession",
            name="context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="存儲額外的會話元數據（如標題、自定義數據等）",
                verbose_name="上下文資料",
            ),
        ),
        migrations.AlterField(
            model_name="aisession",
            name="user",
            field=models.ForeignKey(
                help_text="該會話所屬的用戶",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用戶",
            ),
        ),
    ]
