# Generated by Django 4.2.30 on 2026-04-15 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0009_fix_executed_problem_fk_uuid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AIPendingAction",
        ),
    ]
