# Generated by Django 4.2.30 on 2026-04-15 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0010_remove_aipendingaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiexecutionlog",
            name="model_used",
            field=models.CharField(
                default="deepseek-r1",
                help_text="使用的 Claude 模型版本",
                max_length=50,
                verbose_name="使用的模型",
            ),
        ),
        migrations.CreateModel(
            name="UserAICredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_input_tokens",
                    models.BigIntegerField(default=0, verbose_name="累計輸入 tokens"),
                ),
                (
                    "total_output_tokens",
                    models.BigIntegerField(default=0, verbose_name="累計輸出 tokens"),
                ),
                (
                    "total_requests",
                    models.IntegerField(default=0, verbose_name="累計請求數"),
                ),
                (
                    "total_cost_cents",
                    models.BigIntegerField(default=0, verbose_name="累計費用 (cents)"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最後更新"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_credit",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Credit 使用紀錄",
                "verbose_name_plural": "AI Credit 使用紀錄",
            },
        ),
    ]
