# Generated by Django 4.2.30 on 2026-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0012_aichatrun_aistreamevent"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aichatrun",
            new_name="ai_aichatru_user_id_a770b6_idx",
            old_name="ai_aichatru_user_id_bddaba_idx",
        ),
        migrations.RenameIndex(
            model_name="aichatrun",
            new_name="ai_aichatru_session_fb133c_idx",
            old_name="ai_aichatru_session_1b7859_idx",
        ),
        migrations.RenameIndex(
            model_name="aichatrun",
            new_name="ai_aichatru_status_90b8f5_idx",
            old_name="ai_aichatru_status_34e8bd_idx",
        ),
        migrations.RenameIndex(
            model_name="aistreamevent",
            new_name="ai_aistream_run_id_ea539e_idx",
            old_name="ai_aistrea_run_id_19c03c_idx",
        ),
        migrations.RenameIndex(
            model_name="aistreamevent",
            new_name="ai_aistream_event_t_0e7ceb_idx",
            old_name="ai_aistrea_event_t_ce4d9c_idx",
        ),
        migrations.AlterField(
            model_name="aiexecutionlog",
            name="model_used",
            field=models.CharField(
                default="deepseek-r1",
                help_text="使用的 LLM 模型版本",
                max_length=50,
                verbose_name="使用的模型",
            ),
        ),
    ]
