# Generated by Django 4.2.30 on 2026-04-20 08:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0014_useraicredit_total_credits"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        help_text="SOP 階段識別（例：rubric、raw_answers、calibration、graded、final_delta）",
                        max_length=64,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "object_key",
                    models.CharField(
                        help_text="MinIO 物件 key：ai-artifacts/{session_id}/{step}/{filename}",
                        max_length=512,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="application/octet-stream", max_length=100
                    ),
                ),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "checksum",
                    models.CharField(
                        blank=True, help_text="內容 sha256，用於完整性檢查", max_length=64
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="自由欄位：artifact_type、rubric 摘要、評分進度等",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        help_text="最近一次寫入此 artifact 的 run（保留紀錄，不影響讀取）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="ai.aichatrun",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="ai.aisession",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "step"],
                        name="ai_aiartifa_session_f4f52e_idx",
                    ),
                    models.Index(
                        fields=["session", "-updated_at"],
                        name="ai_aiartifa_session_54f3dc_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="aiartifact",
            constraint=models.UniqueConstraint(
                fields=("session", "step", "filename"),
                name="uniq_ai_artifact_session_step_filename",
            ),
        ),
    ]
