# Generated by Django 4.2.30 on 2026-04-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0015_aiartifact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aichatrun",
            name="question_answer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="aichatrun",
            name="question_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="aichatrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("awaiting_approval", "Awaiting approval"),
                    ("awaiting_user_answer", "Awaiting user answer"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                max_length=32,
            ),
        ),
    ]
