# Generated by Django 4.2.30 on 2026-04-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0016_aichatrun_question_answer_aichatrun_question_payload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aichatrun",
            name="model_id",
            field=models.CharField(default="deepseek-v4", max_length=50),
        ),
        migrations.AlterField(
            model_name="aiexecutionlog",
            name="model_used",
            field=models.CharField(
                default="deepseek-v4",
                help_text="使用的 LLM 模型版本",
                max_length=50,
                verbose_name="使用的模型",
            ),
        ),
    ]
