# Generated by Django 4.2.26 on 2025-11-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contests", "0001_initial"),
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreenEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("blur", "視窗失焦"),
                            ("focus", "視窗聚焦"),
                            ("copy", "複製"),
                            ("paste", "貼上"),
                            ("fullscreen_exit", "退出全螢幕"),
                        ],
                        max_length=20,
                        verbose_name="事件類型",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="發生時間"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="詳細資訊"),
                ),
            ],
            options={
                "verbose_name": "螢幕事件",
                "verbose_name_plural": "螢幕事件",
                "db_table": "screen_events",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python 3.11"),
                            ("cpp", "C++ 20"),
                            ("c", "C 11"),
                            ("java", "Java 17"),
                        ],
                        max_length=20,
                        verbose_name="語言",
                    ),
                ),
                ("code", models.TextField(verbose_name="程式碼")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("judging", "Judging"),
                            ("AC", "Accepted"),
                            ("WA", "Wrong Answer"),
                            ("TLE", "Time Limit Exceeded"),
                            ("MLE", "Memory Limit Exceeded"),
                            ("RE", "Runtime Error"),
                            ("CE", "Compilation Error"),
                            ("SE", "System Error"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="狀態",
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="分數")),
                ("exec_time", models.IntegerField(default=0, verbose_name="執行時間 (ms)")),
                (
                    "memory_usage",
                    models.IntegerField(default=0, verbose_name="記憶體使用 (KB)"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="錯誤訊息")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="提交時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="contests.contest",
                        verbose_name="考試",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="problems.problem",
                        verbose_name="題目",
                    ),
                ),
            ],
            options={
                "verbose_name": "提交記錄",
                "verbose_name_plural": "提交記錄",
                "db_table": "submissions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Accepted"),
                            ("WA", "Wrong Answer"),
                            ("TLE", "Time Limit Exceeded"),
                            ("MLE", "Memory Limit Exceeded"),
                            ("RE", "Runtime Error"),
                            ("SE", "System Error"),
                        ],
                        max_length=10,
                        verbose_name="狀態",
                    ),
                ),
                ("exec_time", models.IntegerField(default=0, verbose_name="執行時間 (ms)")),
                (
                    "memory_usage",
                    models.IntegerField(default=0, verbose_name="記憶體使用 (KB)"),
                ),
                ("output", models.TextField(blank=True, verbose_name="輸出")),
                ("error_message", models.TextField(blank=True, verbose_name="錯誤訊息")),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="submissions.submission",
                        verbose_name="提交記錄",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_results",
                        to="problems.testcase",
                        verbose_name="測試案例",
                    ),
                ),
            ],
            options={
                "verbose_name": "評測結果",
                "verbose_name_plural": "評測結果",
                "db_table": "submission_results",
            },
        ),
    ]
