# Generated by Django 4.2.26 on 2025-11-26 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="使用者",
            ),
        ),
        migrations.AddField(
            model_name="screenevent",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screen_events",
                to="submissions.submission",
                verbose_name="提交記錄",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submissionresult",
            unique_together={("submission", "test_case")},
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["user", "problem"], name="submissions_user_id_34eafe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["status"], name="submissions_status_dcc854_idx"),
        ),
    ]
