# Generated by Django 4.2.30 on 2026-07-13 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_source_type(apps, schema_editor):
    Submission = apps.get_model("submissions", "Submission")
    Submission.objects.filter(contest__isnull=False).update(source_type="contest")


def reverse_populate_source_type(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    replaces = [('submissions', '0002_initial'), ('submissions', '0003_add_is_test_field'), ('submissions', '0004_submission_source_type'), ('submissions', '0005_populate_source_type'), ('submissions', '0006_submission_custom_test_cases'), ('submissions', '0007_alter_submissionresult_unique_together_and_more'), ('submissions', '0008_alter_submissionresult_expected_output_and_more'), ('submissions', '0009_alter_submissionresult_test_case'), ('submissions', '0010_add_performance_indexes'), ('submissions', '0011_alter_submission_status')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0005_tag_problem_tags'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AddField(
            model_name='screenevent',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_events', to='submissions.submission', verbose_name='提交記錄'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionresult',
            unique_together={('submission', 'test_case')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem'], name='submissions_user_id_34eafe_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submissions_status_dcc854_idx'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='測試提交'),
        ),
        migrations.AddField(
            model_name='submission',
            name='source_type',
            field=models.CharField(choices=[('practice', 'Practice'), ('contest', 'Contest')], db_index=True, default='practice', max_length=10, verbose_name='來源類型'),
        ),
        migrations.RunPython(
            code=populate_source_type,
            reverse_code=reverse_populate_source_type,
        ),
        migrations.AddField(
            model_name='submission',
            name='custom_test_cases',
            field=models.JSONField(blank=True, default=list, verbose_name='自訂測資'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionresult',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_results', to='problems.testcase', verbose_name='測試案例'),
        ),
        migrations.AddField(
            model_name='submissionresult',
            name='expected_output',
            field=models.TextField(blank=True, null=True, verbose_name='預期輸出'),
        ),
        migrations.AddField(
            model_name='submissionresult',
            name='input_data',
            field=models.TextField(blank=True, null=True, verbose_name='輸入資料'),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_results', to='problems.testcase', verbose_name='測試案例'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['source_type', 'is_test', '-created_at'], name='sub_src_test_created_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['contest', 'source_type', '-created_at'], name='sub_contest_src_created_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', '-created_at'], name='sub_problem_created_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', '-created_at'], name='sub_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-created_at'], name='sub_user_created_idx'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('judging', 'Judging'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error'), ('KR', 'Keyword Restriction'), ('SE', 'System Error')], db_index=True, default='pending', max_length=10, verbose_name='狀態'),
        ),
    ]
