# Generated by Django 4.2.26 on 2025-11-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_test",
            field=models.BooleanField(default=False, verbose_name="測試提交"),
        ),
    ]
