# Generated by Django 4.2.26 on 2025-11-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0003_add_is_test_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="source_type",
            field=models.CharField(
                choices=[("practice", "Practice"), ("contest", "Contest")],
                db_index=True,
                default="practice",
                max_length=10,
                verbose_name="來源類型",
            ),
        ),
    ]
