# Generated by Django 4.2.26 on 2025-12-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0005_populate_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="custom_test_cases",
            field=models.JSONField(blank=True, default=list, verbose_name="自訂測資"),
        ),
    ]
