# Generated by Django 4.2.26 on 2025-12-06 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0005_tag_problem_tags"),
        ("submissions", "0006_submission_custom_test_cases"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="submissionresult",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="submissionresult",
            name="expected_output",
            field=models.TextField(blank=True, verbose_name="預期輸出"),
        ),
        migrations.AddField(
            model_name="submissionresult",
            name="input_data",
            field=models.TextField(blank=True, verbose_name="輸入資料"),
        ),
        migrations.AlterField(
            model_name="submissionresult",
            name="test_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission_results",
                to="problems.testcase",
                verbose_name="測試案例",
            ),
        ),
    ]
