# Generated by Django 4.2.26 on 2025-12-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0007_alter_submissionresult_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionresult",
            name="expected_output",
            field=models.TextField(blank=True, null=True, verbose_name="預期輸出"),
        ),
        migrations.AlterField(
            model_name="submissionresult",
            name="input_data",
            field=models.TextField(blank=True, null=True, verbose_name="輸入資料"),
        ),
    ]
