# Generated by Django 4.2.27 on 2025-12-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0005_tag_problem_tags"),
        ("submissions", "0008_alter_submissionresult_expected_output_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionresult",
            name="test_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_results",
                to="problems.testcase",
                verbose_name="測試案例",
            ),
        ),
    ]
