# Generated by Django 4.2.27 on 2025-12-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0010_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("judging", "Judging"),
                    ("AC", "Accepted"),
                    ("WA", "Wrong Answer"),
                    ("TLE", "Time Limit Exceeded"),
                    ("MLE", "Memory Limit Exceeded"),
                    ("RE", "Runtime Error"),
                    ("CE", "Compilation Error"),
                    ("KR", "Keyword Restriction"),
                    ("SE", "System Error"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="狀態",
            ),
        ),
    ]
