# Generated by Codex on 2026-03-28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0013_submission_problem_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="lab",
        ),
    ]
