# Generated by Codex on 2026-03-28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0014_remove_submission_lab"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="submission",
            name="sub_lab_created_idx",
        ),
    ]
