# Generated by Codex on 2026-03-28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0002_labproblem_problem_uuid"),
        ("submissions", "0014_remove_submission_lab"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LabProblem",
        ),
        migrations.DeleteModel(
            name="Lab",
        ),
    ]
