# Generated by Django 4.2.29 on 2026-03-17 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contests", "0045_add_screen_share_interrupted_event_type"),
        ("problems", "0013_remove_problem_problems_is_visi_40a652_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[("coding", "Coding"), ("exam", "Exam")],
                        db_index=True,
                        default="coding",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("prompt", models.TextField(blank=True, default="")),
                ("options", models.JSONField(blank=True, default=list)),
                ("correct_answer", models.JSONField(blank=True, null=True)),
                ("score", models.PositiveIntegerField(default=100)),
                ("order", models.IntegerField(default=0)),
                ("difficulty", models.CharField(default="medium", max_length=10)),
                ("time_limit", models.IntegerField(default=1000)),
                ("memory_limit", models.IntegerField(default=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "questions",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionCodingExt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translations", models.JSONField(blank=True, default=list)),
                ("test_cases", models.JSONField(blank=True, default=list)),
                ("language_configs", models.JSONField(blank=True, default=list)),
                ("forbidden_keywords", models.JSONField(blank=True, default=list)),
                ("required_keywords", models.JSONField(blank=True, default=list)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_ext",
                        to="question_bank.question",
                    ),
                ),
            ],
            options={
                "db_table": "questions_coding_ext",
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[("coding", "Coding"), ("exam", "Exam")],
                        db_index=True,
                        default="coding",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        db_index=True,
                        default="private",
                        max_length=20,
                    ),
                ),
                ("verified", models.BooleanField(db_index=True, default=False)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means platform-managed official bank.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_banks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "question_banks",
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="question_bank.questionbank",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_bank_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="source_exam_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="synced_question_bank_entries",
                to="contests.examquestion",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="source_problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="synced_question_bank_entries",
                to="problems.problem",
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["owner", "category"], name="question_ba_owner_i_4e1d12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["visibility", "verified"], name="question_ba_visibil_e871b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["bank", "order"], name="questions_bank_id_07865d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["question_type"], name="questions_questio_8af709_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["source_problem"], name="questions_source__aa7397_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["source_exam_question"], name="questions_source__a31de3_idx"
            ),
        ),
    ]
