# Generated by Django 4.2.30 on 2026-09-15 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContestQuestionBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "binding_type",
                    models.CharField(
                        choices=[
                            ("coding", "Coding"),
                            ("true_false", "True/False"),
                            ("single_choice", "Single Choice"),
                            ("multiple_choice", "Multiple Choice"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("reading_set", "Reading Set"),
                        ],
                        max_length=32,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("score", models.PositiveIntegerField(default=100)),
                ("source_bank_id", models.UUIDField(blank=True, null=True)),
                (
                    "source_bank_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("source_question_id", models.UUIDField(blank=True, null=True)),
                (
                    "source_mode",
                    models.CharField(blank=True, default="manual", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "contest_question_bindings",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("coding", "Coding"),
                            ("true_false", "True/False"),
                            ("single_choice", "Single Choice"),
                            ("multiple_choice", "Multiple Choice"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("reading_set", "Reading Set"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("prompt", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "question_assets",
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("icon", models.CharField(blank=True, default="", max_length=32)),
                ("cover_url", models.URLField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[("coding", "Coding"), ("exam", "Exam")],
                        db_index=True,
                        default="coding",
                        max_length=20,
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "question_banks",
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBankMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "question_bank_memberships",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("prompt", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "question_versions",
                "ordering": ["-version_number", "-created_at"],
            },
        ),
    ]
