# Generated by Django 4.2.29 on 2026-03-17

import uuid
from django.db import migrations, models


def populate_question_bank_uuids(apps, schema_editor):
    QuestionBank = apps.get_model("question_bank", "QuestionBank")
    Question = apps.get_model("question_bank", "Question")

    for bank in QuestionBank.objects.filter(uuid__isnull=True).only("id"):
        bank.uuid = uuid.uuid4()
        bank.save(update_fields=["uuid"])

    for question in Question.objects.filter(uuid__isnull=True).only("id"):
        question.uuid = uuid.uuid4()
        question.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                editable=False,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                editable=False,
                null=True,
            ),
        ),
        migrations.RunPython(
            populate_question_bank_uuids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
    ]
