# Generated by Django 4.2.30 on 2026-09-15 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("question_bank", "0001_baseline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contests", "0003_baseline"),
        ("problems", "0002_baseline"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_question_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="questionversion",
            name="question_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="question_bank.questionasset",
            ),
        ),
        migrations.AddField(
            model_name="questionbankmembership",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_question_bank_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="questionbankmembership",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_memberships",
                to="question_bank.questionbank",
            ),
        ),
        migrations.AddField(
            model_name="questionbankmembership",
            name="question_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_memberships",
                to="question_bank.questionasset",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_banks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="questionasset",
            name="latest_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="question_bank.questionversion",
            ),
        ),
        migrations.AddField(
            model_name="questionasset",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contestquestionbinding",
            name="coding_problem",
            field=models.ForeignKey(
                blank=True,
                help_text="For coding-type bindings: the execution adapter that owns test cases, etc.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contest_bindings",
                to="problems.codingproblem",
            ),
        ),
        migrations.AddField(
            model_name="contestquestionbinding",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_bindings",
                to="contests.contest",
            ),
        ),
        migrations.AddField(
            model_name="contestquestionbinding",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_contest_question_bindings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contestquestionbinding",
            name="exam_question",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="question_binding",
                to="contests.examquestion",
            ),
        ),
        migrations.AddField(
            model_name="contestquestionbinding",
            name="question_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contest_bindings",
                to="question_bank.questionasset",
            ),
        ),
        migrations.AddField(
            model_name="contestquestionbinding",
            name="question_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contest_bindings",
                to="question_bank.questionversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionversion",
            constraint=models.UniqueConstraint(
                fields=("question_asset", "version_number"),
                name="unique_question_version_per_asset",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionbankmembership",
            constraint=models.UniqueConstraint(
                fields=("bank", "question_asset"),
                name="unique_bank_membership_per_asset",
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["owner", "category"], name="question_ba_owner_i_4e1d12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionasset",
            index=models.Index(
                fields=["owner", "asset_type"], name="question_as_owner_i_27ccd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contestquestionbinding",
            index=models.Index(
                fields=["contest", "order"], name="contest_que_contest_f33ed3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contestquestionbinding",
            index=models.Index(
                fields=["question_asset"], name="contest_que_questio_c4a50d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contestquestionbinding",
            index=models.Index(
                fields=["coding_problem"], name="contest_que_coding__b1149c_idx"
            ),
        ),
    ]
