# Generated by Django 4.2.29 on 2026-03-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank", "0002_add_uuid_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
