# Generated by Django 4.2.29 on 2026-03-28 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank", "0007_question_pk_uuid_cutover"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="question",
            new_name="questions_source__bc205f_idx",
            old_name="questions_source__unified_idx",
        ),
        migrations.RenameIndex(
            model_name="questionbank",
            new_name="question_ba_review__a85cf3_idx",
            old_name="question_ba_review__4a2e8d_idx",
        ),
    ]
