# Generated by Django 4.2.29 on 2026-03-29 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "question_bank",
            "0008_rename_questions_source__unified_idx_questions_source__bc205f_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="legacy_int_id",
        ),
    ]
