# Generated by Django 4.2.30 on 2026-04-10 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "question_bank",
            "0014_rename_contest_que_coding__a1b2c3_idx_contest_que_coding__b1149c_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionBankSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="question_bank.questionbank",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "question_bank_subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="questionbanksubscription",
            constraint=models.UniqueConstraint(
                fields=("user", "bank"), name="unique_subscription_per_user_bank"
            ),
        ),
    ]
