# Generated by Django 4.2.30 on 2026-04-11 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("question_bank", "0015_add_question_bank_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contestquestionbinding",
            name="legacy_contest_problem",
        ),
    ]
